deploy: 1a657f7e8ed180683b16206c0fed1d9e67de4675

diff --git a/target/docker/perturbation/batch_correction_scgen/batch_correction_scgen b/target/docker/perturbation/batch_correction_scgen/batch_correction_scgen
--- a/target/docker/perturbation/batch_correction_scgen/batch_correction_scgen
+++ b/target/docker/perturbation/batch_correction_scgen/batch_correction_scgen
@@ -174,12 +174,12 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --perturbation_data"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --perturbation_data_bc"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
 }
@@ -406,9 +406,9 @@ ENTRYPOINT []
  
 RUN :
 LABEL org.opencontainers.image.description="Companion container for running component perturbation batch_correction_scgen"
-LABEL org.opencontainers.image.created="2024-08-09T15:59:50Z"
+LABEL org.opencontainers.image.created="2024-08-10T13:22:52Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="ccf72dd57328a03c8be421f6b05f1f32825fd395"
+LABEL org.opencontainers.image.revision="1a657f7e8ed180683b16206c0fed1d9e67de4675"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -707,6 +707,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
+  ViashError '--perturbation_data' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_PERTURBATION_DATA_BC+x} ]; then
+  ViashError '--perturbation_data_bc' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -728,21 +736,9 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   exit 1
 fi
 
-# filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_PERTURBATION_DATA_BC+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA_BC="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
   ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
-  exit 1
-fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
-  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
   exit 1
 fi
 
@@ -790,6 +786,11 @@ if [[ -n "$VIASH_META_MEMORY_PB" ]]; then
   fi
 fi
 
+# create parent directories of output files, if so desired
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -d "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")"
+fi
+
 # detect volumes from file arguments
 VIASH_CHOWN_VARS=()
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
@@ -799,6 +800,7 @@ fi
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_PERTURBATION_DATA_BC")" )
   VIASH_PAR_PERTURBATION_DATA_BC=$(ViashAutodetectMount "$VIASH_PAR_PERTURBATION_DATA_BC")
+  VIASH_CHOWN_VARS+=( "$VIASH_PAR_PERTURBATION_DATA_BC" )
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -938,6 +940,13 @@ if [ ! -z "$VIASH_META_CONFIG" ]; then
 fi
 if [ ! -z "$VIASH_META_TEMP_DIR" ]; then
   VIASH_META_TEMP_DIR=$(ViashStripAutomount "$VIASH_META_TEMP_DIR")
+fi
+
+
+# check whether required files exist
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
+  ViashError "Output file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
+  exit 1
 fi
 
 
diff --git a/target/docker/perturbation/normalization/normalization b/target/docker/perturbation/normalization/normalization
--- a/target/docker/perturbation/normalization/normalization
+++ b/target/docker/perturbation/normalization/normalization
@@ -174,12 +174,12 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --pseudobulked_data_f"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources_local/pseudobulked_data_f"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --perturbation_data"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
 }
@@ -408,9 +408,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "sctk==0.2.2"
 
 LABEL org.opencontainers.image.description="Companion container for running component perturbation normalization"
-LABEL org.opencontainers.image.created="2024-08-09T15:59:49Z"
+LABEL org.opencontainers.image.created="2024-08-10T13:22:51Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="ccf72dd57328a03c8be421f6b05f1f32825fd395"
+LABEL org.opencontainers.image.revision="1a657f7e8ed180683b16206c0fed1d9e67de4675"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -709,6 +709,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA_F+x} ]; then
+  ViashError '--pseudobulked_data_f' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
+  ViashError '--perturbation_data' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -730,21 +738,9 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   exit 1
 fi
 
-# filling in defaults
-if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA_F+x} ]; then
-  VIASH_PAR_PSEUDOBULKED_DATA_F="resources_local/pseudobulked_data_f"
-fi
-if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_PSEUDOBULKED_DATA_F" ] && [ ! -e "$VIASH_PAR_PSEUDOBULKED_DATA_F" ]; then
   ViashError "Input file '$VIASH_PAR_PSEUDOBULKED_DATA_F' does not exist."
-  exit 1
-fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
-  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
   exit 1
 fi
 
@@ -792,6 +788,11 @@ if [[ -n "$VIASH_META_MEMORY_PB" ]]; then
   fi
 fi
 
+# create parent directories of output files, if so desired
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -d "$(dirname "$VIASH_PAR_PERTURBATION_DATA")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_PERTURBATION_DATA")"
+fi
+
 # detect volumes from file arguments
 VIASH_CHOWN_VARS=()
 if [ ! -z "$VIASH_PAR_PSEUDOBULKED_DATA_F" ]; then
@@ -801,6 +802,7 @@ fi
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_PERTURBATION_DATA")" )
   VIASH_PAR_PERTURBATION_DATA=$(ViashAutodetectMount "$VIASH_PAR_PERTURBATION_DATA")
+  VIASH_CHOWN_VARS+=( "$VIASH_PAR_PERTURBATION_DATA" )
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -941,6 +943,13 @@ if [ ! -z "$VIASH_META_CONFIG" ]; then
 fi
 if [ ! -z "$VIASH_META_TEMP_DIR" ]; then
   VIASH_META_TEMP_DIR=$(ViashStripAutomount "$VIASH_META_TEMP_DIR")
+fi
+
+
+# check whether required files exist
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
+  ViashError "Output file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
+  exit 1
 fi
 
 
diff --git a/target/native/perturbation/batch_correction_scgen/batch_correction_scgen b/target/native/perturbation/batch_correction_scgen/batch_correction_scgen
--- a/target/native/perturbation/batch_correction_scgen/batch_correction_scgen
+++ b/target/native/perturbation/batch_correction_scgen/batch_correction_scgen
@@ -174,12 +174,12 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --perturbation_data"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --perturbation_data_bc"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
 }
@@ -310,6 +310,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
+  ViashError '--perturbation_data' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_PERTURBATION_DATA_BC+x} ]; then
+  ViashError '--perturbation_data_bc' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -331,21 +339,9 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   exit 1
 fi
 
-# filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_PERTURBATION_DATA_BC+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA_BC="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
   ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
-  exit 1
-fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
-  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
   exit 1
 fi
 
@@ -391,6 +387,11 @@ if [[ -n "$VIASH_META_MEMORY_PB" ]]; then
     ViashError 'memory_pb' has to be a long. Use "--help" to get more information on the parameters.
     exit 1
   fi
+fi
+
+# create parent directories of output files, if so desired
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -d "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")"
 fi
 
 
@@ -472,6 +473,13 @@ python -B "\$tempscript" &
 wait "\$!"
 
 VIASHEOF
+
+
+# check whether required files exist
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
+  ViashError "Output file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
+  exit 1
+fi
 
 
 exit 0
diff --git a/target/native/perturbation/batch_correction_seurat/batch_correction_seurat b/target/native/perturbation/batch_correction_seurat/batch_correction_seurat
--- a/target/native/perturbation/batch_correction_seurat/batch_correction_seurat
+++ b/target/native/perturbation/batch_correction_seurat/batch_correction_seurat
@@ -174,11 +174,11 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --perturbation_data_n"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --perturbation_data_bc"
-  echo "        type: file, file must exist"
+  echo "        type: file, output, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
 }
 
@@ -308,6 +308,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PERTURBATION_DATA_N+x} ]; then
+  ViashError '--perturbation_data_n' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -330,9 +334,6 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
 fi
 
 # filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_DATA_N+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA_N="resources/grn-benchmark/perturbation_data.h5ad"
-fi
 if [ -z ${VIASH_PAR_PERTURBATION_DATA_BC+x} ]; then
   VIASH_PAR_PERTURBATION_DATA_BC="resources/grn-benchmark/perturbation_data.h5ad"
 fi
@@ -340,10 +341,6 @@ fi
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_N" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_N" ]; then
   ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA_N' does not exist."
-  exit 1
-fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
-  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
   exit 1
 fi
 
@@ -389,6 +386,11 @@ if [[ -n "$VIASH_META_MEMORY_PB" ]]; then
     ViashError 'memory_pb' has to be a long. Use "--help" to get more information on the parameters.
     exit 1
   fi
+fi
+
+# create parent directories of output files, if so desired
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -d "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_PERTURBATION_DATA_BC")"
 fi
 
 
@@ -479,6 +481,13 @@ Rscript "\$tempscript" &
 wait "\$!"
 
 VIASHEOF
+
+
+# check whether required files exist
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA_BC" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA_BC" ]; then
+  ViashError "Output file '$VIASH_PAR_PERTURBATION_DATA_BC' does not exist."
+  exit 1
+fi
 
 
 exit 0
diff --git a/target/native/perturbation/sc_counts/sc_counts b/target/native/perturbation/sc_counts/sc_counts
--- a/target/native/perturbation/sc_counts/sc_counts
+++ b/target/native/perturbation/sc_counts/sc_counts
@@ -174,17 +174,17 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --perturbation_counts"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources/datasets_raw/perturbation_counts.h5ad"
   echo "        example: resources_test/datasets_raw/perturbation_counts.h5ad"
   echo ""
   echo "    --pseudobulked_data"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        default: resources_local/pseudobulked_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --pseudobulked_data_f"
-  echo "        type: file, output, file must exist"
+  echo "        type: file, required parameter, output, file must exist"
   echo "        default: resources_local/pseudobulked_data_f.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
 }
@@ -326,6 +326,18 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PERTURBATION_COUNTS+x} ]; then
+  ViashError '--perturbation_counts' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA+x} ]; then
+  ViashError '--pseudobulked_data' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA_F+x} ]; then
+  ViashError '--pseudobulked_data_f' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -345,17 +357,6 @@ fi
 if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   ViashError 'temp_dir' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
-fi
-
-# filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_COUNTS+x} ]; then
-  VIASH_PAR_PERTURBATION_COUNTS="resources/datasets_raw/perturbation_counts.h5ad"
-fi
-if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA+x} ]; then
-  VIASH_PAR_PSEUDOBULKED_DATA="resources_local/pseudobulked_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_PSEUDOBULKED_DATA_F+x} ]; then
-  VIASH_PAR_PSEUDOBULKED_DATA_F="resources_local/pseudobulked_data_f.h5ad"
 fi
 
 # check whether required files exist
