deploy: 9e3e9a9a72bad9b7ebce077e2ca86a88a08a8795

diff --git a/target/executable/control_methods/negative_control/negative_control b/target/executable/control_methods/negative_control/negative_control
--- a/target/executable/control_methods/negative_control/negative_control
+++ b/target/executable/control_methods/negative_control/negative_control
@@ -456,9 +456,9 @@ RUN pip install --upgrade pip && \
 RUN pip install --upgrade pip
 
 LABEL org.opencontainers.image.description="Companion container for running component control_methods negative_control"
-LABEL org.opencontainers.image.created="2025-02-09T22:44:09Z"
+LABEL org.opencontainers.image.created="2025-02-10T12:54:51Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="771a896bfa88cdfad501d1605fdf4f77d6ed92bd"
+LABEL org.opencontainers.image.revision="9e3e9a9a72bad9b7ebce077e2ca86a88a08a8795"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -592,7 +592,7 @@ function ViashHelp {
   echo "        example: resources_test/grn_models/op/collectri.h5ad"
   echo ""
   echo "    --tf_all"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources_test/grn_benchmark/prior/tf_all.csv"
   echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
   echo ""
@@ -602,7 +602,7 @@ function ViashHelp {
   echo ""
   echo "    --num_workers"
   echo "        type: integer"
-  echo "        default: 4"
+  echo "        default: 20"
   echo ""
   echo "    --temp_dir"
   echo "        type: string"
@@ -954,6 +954,10 @@ if [ -z ${VIASH_PAR_RNA+x} ]; then
   ViashError '--rna' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_NAME+x} ]; then
   ViashError 'name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -980,14 +984,11 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
 fi
 
 # filling in defaults
-if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
-  VIASH_PAR_TF_ALL="resources_test/grn_benchmark/prior/tf_all.csv"
-fi
 if [ -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then
   VIASH_PAR_MAX_N_LINKS="50000"
 fi
 if [ -z ${VIASH_PAR_NUM_WORKERS+x} ]; then
-  VIASH_PAR_NUM_WORKERS="4"
+  VIASH_PAR_NUM_WORKERS="20"
 fi
 if [ -z ${VIASH_PAR_TEMP_DIR+x} ]; then
   VIASH_PAR_TEMP_DIR="output/temdir"
diff --git a/target/executable/workflows/grn_inference_celloracle/grn_inference_celloracle b/target/executable/workflows/grn_inference_celloracle/grn_inference_celloracle
--- a/target/executable/workflows/grn_inference_celloracle/grn_inference_celloracle
+++ b/target/executable/workflows/grn_inference_celloracle/grn_inference_celloracle
@@ -193,7 +193,7 @@ function ViashHelp {
   echo "        example: resources_test/grn_models/op/collectri.h5ad"
   echo ""
   echo "    --tf_all"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources_test/grn_benchmark/prior/tf_all.csv"
   echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
   echo ""
@@ -203,7 +203,7 @@ function ViashHelp {
   echo ""
   echo "    --num_workers"
   echo "        type: integer"
-  echo "        default: 4"
+  echo "        default: 20"
   echo ""
   echo "    --temp_dir"
   echo "        type: string"
@@ -490,6 +490,10 @@ if [ -z ${VIASH_PAR_RNA+x} ]; then
   ViashError '--rna' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_NAME+x} ]; then
   ViashError 'name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -516,14 +520,11 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
 fi
 
 # filling in defaults
-if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
-  VIASH_PAR_TF_ALL="resources_test/grn_benchmark/prior/tf_all.csv"
-fi
 if [ -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then
   VIASH_PAR_MAX_N_LINKS="50000"
 fi
 if [ -z ${VIASH_PAR_NUM_WORKERS+x} ]; then
-  VIASH_PAR_NUM_WORKERS="4"
+  VIASH_PAR_NUM_WORKERS="20"
 fi
 if [ -z ${VIASH_PAR_TEMP_DIR+x} ]; then
   VIASH_PAR_TEMP_DIR="output/temdir"
