deploy: 5f374ff0c4b5b4ea190a85b2a9a97395a3dd452e

diff --git a/target/docker/metrics/regression_1/regression_1 b/target/docker/metrics/regression_1/regression_1
--- a/target/docker/metrics/regression_1/regression_1
+++ b/target/docker/metrics/regression_1/regression_1
@@ -231,6 +231,10 @@ function ViashHelp {
   echo "        type: boolean"
   echo "        default: false"
   echo ""
+  echo "    --dataset_id"
+  echo "        type: string, required parameter"
+  echo "        default: op"
+  echo ""
   echo "    --binarize"
   echo "        type: boolean"
   echo "        default: true"
@@ -461,9 +465,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_1"
-LABEL org.opencontainers.image.created="2024-12-23T19:51:56Z"
+LABEL org.opencontainers.image.created="2025-01-05T19:18:43Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="d2539c6daf49e238123d0673ab6757cff6260cbc"
+LABEL org.opencontainers.image.revision="5f374ff0c4b5b4ea190a85b2a9a97395a3dd452e"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -776,6 +780,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_APPLY_SKELETON=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --dataset_id)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --dataset_id. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --dataset_id=*)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id=*\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --binarize)
             [ -n "$VIASH_PAR_BINARIZE" ] && ViashError Bad arguments for option \'--binarize\': \'$VIASH_PAR_BINARIZE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_BINARIZE="$2"
@@ -911,6 +926,10 @@ if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
 fi
 if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
   ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
+  ViashError '--dataset_id' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
@@ -1177,6 +1196,7 @@ par = {
   'verbose': $( if [ ! -z ${VIASH_PAR_VERBOSE+x} ]; then echo "int(r'${VIASH_PAR_VERBOSE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'skeleton': $( if [ ! -z ${VIASH_PAR_SKELETON+x} ]; then echo "r'${VIASH_PAR_SKELETON//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'dataset_id': $( if [ ! -z ${VIASH_PAR_DATASET_ID+x} ]; then echo "r'${VIASH_PAR_DATASET_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'binarize': $( if [ ! -z ${VIASH_PAR_BINARIZE+x} ]; then echo "r'${VIASH_PAR_BINARIZE//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
 meta = {
@@ -1249,7 +1269,7 @@ print(metric_ids.shape, metric_values.shape)
 output = ad.AnnData(
     X=np.empty((0, 0)),
     uns={
-        "dataset_id": par["layer"],
+        "dataset_id": par["dataset_id"],
         "method_id": f"reg1-{par['method_id']}",
         "metric_ids": metric_ids,
         "metric_values": metric_values
diff --git a/target/docker/metrics/regression_2/regression_2 b/target/docker/metrics/regression_2/regression_2
--- a/target/docker/metrics/regression_2/regression_2
+++ b/target/docker/metrics/regression_2/regression_2
@@ -231,6 +231,10 @@ function ViashHelp {
   echo "        type: boolean"
   echo "        default: false"
   echo ""
+  echo "    --dataset_id"
+  echo "        type: string, required parameter"
+  echo "        default: op"
+  echo ""
   echo "    --consensus"
   echo "        type: file, required parameter"
   echo "        example: resources_test/prior/op_consensus-num-regulators.json"
@@ -464,9 +468,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_2"
-LABEL org.opencontainers.image.created="2024-12-23T19:51:55Z"
+LABEL org.opencontainers.image.created="2025-01-05T19:18:43Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="d2539c6daf49e238123d0673ab6757cff6260cbc"
+LABEL org.opencontainers.image.revision="5f374ff0c4b5b4ea190a85b2a9a97395a3dd452e"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -779,6 +783,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_APPLY_SKELETON=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --dataset_id)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --dataset_id. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --dataset_id=*)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id=*\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --consensus)
             [ -n "$VIASH_PAR_CONSENSUS" ] && ViashError Bad arguments for option \'--consensus\': \'$VIASH_PAR_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_CONSENSUS="$2"
@@ -925,6 +940,10 @@ if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
 fi
 if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
   ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
+  ViashError '--dataset_id' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_CONSENSUS+x} ]; then
@@ -1197,6 +1216,7 @@ par = {
   'verbose': $( if [ ! -z ${VIASH_PAR_VERBOSE+x} ]; then echo "int(r'${VIASH_PAR_VERBOSE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'skeleton': $( if [ ! -z ${VIASH_PAR_SKELETON+x} ]; then echo "r'${VIASH_PAR_SKELETON//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'dataset_id': $( if [ ! -z ${VIASH_PAR_DATASET_ID+x} ]; then echo "r'${VIASH_PAR_DATASET_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'consensus': $( if [ ! -z ${VIASH_PAR_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
@@ -1245,7 +1265,7 @@ metric_values = output.values[0]
 output = ad.AnnData(
     X=np.empty((0, 0)),
     uns={
-        "dataset_id": str(par["layer"]),
+        "dataset_id": str(par["dataset_id"]),
         "method_id": f"reg2-{par['method_id']}",
         "metric_ids": metric_ids,
         "metric_values": metric_values
