deploy: 85c6435c5128d87ece01e29806151c230a6cb03e

diff --git a/target/docker/metrics/regression_1/regression_1 b/target/docker/metrics/regression_1/regression_1
--- a/target/docker/metrics/regression_1/regression_1
+++ b/target/docker/metrics/regression_1/regression_1
@@ -175,7 +175,6 @@ function ViashHelp {
   echo "Arguments:"
   echo "    --perturbation_data"
   echo "        type: file, file must exist"
-  echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --prediction"
@@ -184,8 +183,11 @@ function ViashHelp {
   echo ""
   echo "    --score"
   echo "        type: file, output, file must exist"
-  echo "        default: output/score.h5ad"
   echo "        example: resources_test/scores/score.h5ad"
+  echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/prior/tf_all.csv"
   echo ""
   echo "    --reg_type"
   echo "        type: string"
@@ -204,11 +206,6 @@ function ViashHelp {
   echo "    --method_id"
   echo "        type: string"
   echo "        example: collectri"
-  echo ""
-  echo "    --tf_all"
-  echo "        type: file, file must exist"
-  echo "        default: resources/prior/tf_all.csv"
-  echo "        example: resources_test/prior/tf_all.csv"
   echo ""
   echo "    --apply_tf"
   echo "        type: boolean"
@@ -452,9 +449,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_1"
-LABEL org.opencontainers.image.created="2024-09-12T18:31:27Z"
+LABEL org.opencontainers.image.created="2024-09-13T08:23:15Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="45144825ebae0977f43a73fc134ba821eb06089b"
+LABEL org.opencontainers.image.revision="85c6435c5128d87ece01e29806151c230a6cb03e"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -646,6 +643,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_SCORE=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --tf_all)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --tf_all=*)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --reg_type)
             [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_REG_TYPE="$2"
@@ -688,17 +696,6 @@ while [[ $# -gt 0 ]]; do
         --method_id=*)
             [ -n "$VIASH_PAR_METHOD_ID" ] && ViashError Bad arguments for option \'--method_id=*\': \'$VIASH_PAR_METHOD_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_METHOD_ID=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --tf_all)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --tf_all=*)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --apply_tf)
@@ -867,6 +864,10 @@ if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
   ViashError '--prediction' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -889,12 +890,6 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
 fi
 
 # filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_SCORE+x} ]; then
-  VIASH_PAR_SCORE="output/score.h5ad"
-fi
 if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
   VIASH_PAR_REG_TYPE="ridge"
 fi
@@ -903,9 +898,6 @@ if [ -z ${VIASH_PAR_SUBSAMPLE+x} ]; then
 fi
 if [ -z ${VIASH_PAR_MAX_WORKERS+x} ]; then
   VIASH_PAR_MAX_WORKERS="4"
-fi
-if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
-  VIASH_PAR_TF_ALL="resources/prior/tf_all.csv"
 fi
 if [ -z ${VIASH_PAR_APPLY_TF+x} ]; then
   VIASH_PAR_APPLY_TF="true"
@@ -1097,11 +1089,11 @@ par = {
   'perturbation_data': $( if [ ! -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then echo "r'${VIASH_PAR_PERTURBATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'prediction': $( if [ ! -z ${VIASH_PAR_PREDICTION+x} ]; then echo "r'${VIASH_PAR_PREDICTION//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'score': $( if [ ! -z ${VIASH_PAR_SCORE+x} ]; then echo "r'${VIASH_PAR_SCORE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'subsample': $( if [ ! -z ${VIASH_PAR_SUBSAMPLE+x} ]; then echo "int(r'${VIASH_PAR_SUBSAMPLE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'max_workers': $( if [ ! -z ${VIASH_PAR_MAX_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_MAX_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'method_id': $( if [ ! -z ${VIASH_PAR_METHOD_ID+x} ]; then echo "r'${VIASH_PAR_METHOD_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'clip_scores': $( if [ ! -z ${VIASH_PAR_CLIP_SCORES+x} ]; then echo "r'${VIASH_PAR_CLIP_SCORES//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
diff --git a/target/docker/metrics/regression_2/regression_2 b/target/docker/metrics/regression_2/regression_2
--- a/target/docker/metrics/regression_2/regression_2
+++ b/target/docker/metrics/regression_2/regression_2
@@ -175,7 +175,6 @@ function ViashHelp {
   echo "Arguments:"
   echo "    --perturbation_data"
   echo "        type: file, file must exist"
-  echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
   echo "        example: resources_test/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --prediction"
@@ -184,8 +183,11 @@ function ViashHelp {
   echo ""
   echo "    --score"
   echo "        type: file, output, file must exist"
-  echo "        default: output/score.h5ad"
   echo "        example: resources_test/scores/score.h5ad"
+  echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/prior/tf_all.csv"
   echo ""
   echo "    --reg_type"
   echo "        type: string"
@@ -205,11 +207,6 @@ function ViashHelp {
   echo "        type: string"
   echo "        example: collectri"
   echo ""
-  echo "    --tf_all"
-  echo "        type: file, file must exist"
-  echo "        default: resources/prior/tf_all.csv"
-  echo "        example: resources_test/prior/tf_all.csv"
-  echo ""
   echo "    --apply_tf"
   echo "        type: boolean"
   echo "        default: true"
@@ -219,18 +216,17 @@ function ViashHelp {
   echo "        default: true"
   echo "        clips the r2 scores for each gene to make them within [0, 1]"
   echo ""
+  echo "    --layer"
+  echo "        type: string"
+  echo "        default: scgen_pearson"
+  echo ""
   echo "    --consensus"
-  echo "        type: file, file must exist"
-  echo "        default: resources/prior/consensus-num-regulators.json"
+  echo "        type: file, required parameter"
   echo "        example: resources_test/prior/consensus-num-regulators.json"
   echo ""
   echo "    --static_only"
   echo "        type: boolean"
   echo "        default: true"
-  echo ""
-  echo "    --layer"
-  echo "        type: string"
-  echo "        default: scgen_pearson"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -457,9 +453,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_2"
-LABEL org.opencontainers.image.created="2024-09-12T18:31:27Z"
+LABEL org.opencontainers.image.created="2024-09-13T08:23:15Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="45144825ebae0977f43a73fc134ba821eb06089b"
+LABEL org.opencontainers.image.revision="85c6435c5128d87ece01e29806151c230a6cb03e"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -651,6 +647,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_SCORE=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --tf_all)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --tf_all=*)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --reg_type)
             [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_REG_TYPE="$2"
@@ -695,17 +702,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_METHOD_ID=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --tf_all)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --tf_all=*)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
         --apply_tf)
             [ -n "$VIASH_PAR_APPLY_TF" ] && ViashError Bad arguments for option \'--apply_tf\': \'$VIASH_PAR_APPLY_TF\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_APPLY_TF="$2"
@@ -728,6 +724,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_CLIP_SCORES=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --layer)
+            [ -n "$VIASH_PAR_LAYER" ] && ViashError Bad arguments for option \'--layer\': \'$VIASH_PAR_LAYER\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_LAYER="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --layer. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --layer=*)
+            [ -n "$VIASH_PAR_LAYER" ] && ViashError Bad arguments for option \'--layer=*\': \'$VIASH_PAR_LAYER\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_LAYER=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --consensus)
             [ -n "$VIASH_PAR_CONSENSUS" ] && ViashError Bad arguments for option \'--consensus\': \'$VIASH_PAR_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_CONSENSUS="$2"
@@ -748,17 +755,6 @@ while [[ $# -gt 0 ]]; do
         --static_only=*)
             [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only=*\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_STATIC_ONLY=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --layer)
-            [ -n "$VIASH_PAR_LAYER" ] && ViashError Bad arguments for option \'--layer\': \'$VIASH_PAR_LAYER\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_LAYER="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --layer. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --layer=*)
-            [ -n "$VIASH_PAR_LAYER" ] && ViashError Bad arguments for option \'--layer=*\': \'$VIASH_PAR_LAYER\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_LAYER=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---setup)
@@ -883,6 +879,14 @@ if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
   ViashError '--prediction' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_CONSENSUS+x} ]; then
+  ViashError '--consensus' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -905,12 +909,6 @@ if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
 fi
 
 # filling in defaults
-if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
-  VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_SCORE+x} ]; then
-  VIASH_PAR_SCORE="output/score.h5ad"
-fi
 if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
   VIASH_PAR_REG_TYPE="ridge"
 fi
@@ -920,23 +918,17 @@ fi
 if [ -z ${VIASH_PAR_MAX_WORKERS+x} ]; then
   VIASH_PAR_MAX_WORKERS="4"
 fi
-if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
-  VIASH_PAR_TF_ALL="resources/prior/tf_all.csv"
-fi
 if [ -z ${VIASH_PAR_APPLY_TF+x} ]; then
   VIASH_PAR_APPLY_TF="true"
 fi
 if [ -z ${VIASH_PAR_CLIP_SCORES+x} ]; then
   VIASH_PAR_CLIP_SCORES="true"
 fi
-if [ -z ${VIASH_PAR_CONSENSUS+x} ]; then
-  VIASH_PAR_CONSENSUS="resources/prior/consensus-num-regulators.json"
+if [ -z ${VIASH_PAR_LAYER+x} ]; then
+  VIASH_PAR_LAYER="scgen_pearson"
 fi
 if [ -z ${VIASH_PAR_STATIC_ONLY+x} ]; then
   VIASH_PAR_STATIC_ONLY="true"
-fi
-if [ -z ${VIASH_PAR_LAYER+x} ]; then
-  VIASH_PAR_LAYER="scgen_pearson"
 fi
 
 # check whether required files exist
@@ -950,10 +942,6 @@ if [ ! -z "$VIASH_PAR_PREDICTION" ] && [ ! -e "$VIASH_PAR_PREDICTION" ]; then
 fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ] && [ ! -e "$VIASH_PAR_TF_ALL" ]; then
   ViashError "Input file '$VIASH_PAR_TF_ALL' does not exist."
-  exit 1
-fi
-if [ ! -z "$VIASH_PAR_CONSENSUS" ] && [ ! -e "$VIASH_PAR_CONSENSUS" ]; then
-  ViashError "Input file '$VIASH_PAR_CONSENSUS' does not exist."
   exit 1
 fi
 
@@ -1128,16 +1116,16 @@ par = {
   'perturbation_data': $( if [ ! -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then echo "r'${VIASH_PAR_PERTURBATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'prediction': $( if [ ! -z ${VIASH_PAR_PREDICTION+x} ]; then echo "r'${VIASH_PAR_PREDICTION//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'score': $( if [ ! -z ${VIASH_PAR_SCORE+x} ]; then echo "r'${VIASH_PAR_SCORE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'subsample': $( if [ ! -z ${VIASH_PAR_SUBSAMPLE+x} ]; then echo "int(r'${VIASH_PAR_SUBSAMPLE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'max_workers': $( if [ ! -z ${VIASH_PAR_MAX_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_MAX_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'method_id': $( if [ ! -z ${VIASH_PAR_METHOD_ID+x} ]; then echo "r'${VIASH_PAR_METHOD_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'clip_scores': $( if [ ! -z ${VIASH_PAR_CLIP_SCORES+x} ]; then echo "r'${VIASH_PAR_CLIP_SCORES//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'consensus': $( if [ ! -z ${VIASH_PAR_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
-  'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
 meta = {
   'functionality_name': $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "r'${VIASH_META_FUNCTIONALITY_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
