deploy: dbe05111aa79f6bc2da8a8f0f10f06d8192b7bc4

diff --git a/target/docker/metrics/regression_1/regression_1 b/target/docker/metrics/regression_1/regression_1
--- a/target/docker/metrics/regression_1/regression_1
+++ b/target/docker/metrics/regression_1/regression_1
@@ -179,7 +179,7 @@ function ViashHelp {
   echo "        example: resources/grn-benchmark/perturbation_data.h5ad"
   echo ""
   echo "    --prediction"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        default: resources/grn_models/collectri.csv"
   echo "        example: resources/grn-benchmark/grn_models/collectri.csv"
   echo ""
@@ -435,9 +435,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_1"
-LABEL org.opencontainers.image.created="2024-08-24T08:49:57Z"
+LABEL org.opencontainers.image.created="2024-08-24T11:23:52Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="a183f16843a73d309e45e7045505827473072750"
+LABEL org.opencontainers.image.revision="dbe05111aa79f6bc2da8a8f0f10f06d8192b7bc4"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -802,6 +802,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
+  ViashError '--prediction' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -826,9 +830,6 @@ fi
 # filling in defaults
 if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
   VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
-fi
-if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
-  VIASH_PAR_PREDICTION="resources/grn_models/collectri.csv"
 fi
 if [ -z ${VIASH_PAR_SCORE+x} ]; then
   VIASH_PAR_SCORE="out/score.h5ad"
