deploy: 59865251f12f474017a9324598224a1bfca78c7c

diff --git a/target/docker/metrics/regression_1/regression_1 b/target/docker/metrics/regression_1/regression_1
--- a/target/docker/metrics/regression_1/regression_1
+++ b/target/docker/metrics/regression_1/regression_1
@@ -180,12 +180,12 @@ function ViashHelp {
   echo ""
   echo "    --prediction"
   echo "        type: file, file must exist"
-  echo "        default: resources/grn-benchmark/grn_models/collectri.csv"
+  echo "        default: resources/grn_models/collectri.csv"
   echo "        example: resources/grn-benchmark/grn_models/collectri.csv"
   echo ""
   echo "    --score"
   echo "        type: file, output, file must exist"
-  echo "        default: output/score.h5ad"
+  echo "        default: out/score.h5ad"
   echo "        example: resources/grn-benchmark/score.csv"
   echo ""
   echo "    --reg_type"
@@ -205,6 +205,10 @@ function ViashHelp {
   echo "    --max_workers"
   echo "        type: integer"
   echo "        default: 4"
+  echo ""
+  echo "    --method_id"
+  echo "        type: string, required parameter"
+  echo "        example: collectri"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -431,9 +435,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_1"
-LABEL org.opencontainers.image.created="2024-08-08T12:09:01Z"
+LABEL org.opencontainers.image.created="2024-08-09T15:52:45Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="f7b438a541c6ef7e1b3c4b39efc3b46135186b86"
+LABEL org.opencontainers.image.revision="59865251f12f474017a9324598224a1bfca78c7c"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -669,6 +673,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_MAX_WORKERS=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --method_id)
+            [ -n "$VIASH_PAR_METHOD_ID" ] && ViashError Bad arguments for option \'--method_id\': \'$VIASH_PAR_METHOD_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_METHOD_ID="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --method_id. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --method_id=*)
+            [ -n "$VIASH_PAR_METHOD_ID" ] && ViashError Bad arguments for option \'--method_id=*\': \'$VIASH_PAR_METHOD_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_METHOD_ID=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         ---setup)
             VIASH_MODE='docker_setup'
             VIASH_DOCKER_SETUP_STRATEGY="$2"
@@ -787,6 +802,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_METHOD_ID+x} ]; then
+  ViashError '--method_id' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -813,10 +832,10 @@ if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
   VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
 fi
 if [ -z ${VIASH_PAR_PREDICTION+x} ]; then
-  VIASH_PAR_PREDICTION="resources/grn-benchmark/grn_models/collectri.csv"
+  VIASH_PAR_PREDICTION="resources/grn_models/collectri.csv"
 fi
 if [ -z ${VIASH_PAR_SCORE+x} ]; then
-  VIASH_PAR_SCORE="output/score.h5ad"
+  VIASH_PAR_SCORE="out/score.h5ad"
 fi
 if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
   VIASH_PAR_REG_TYPE="ridge"
@@ -988,7 +1007,8 @@ par = {
   'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'subsample': $( if [ ! -z ${VIASH_PAR_SUBSAMPLE+x} ]; then echo "int(r'${VIASH_PAR_SUBSAMPLE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
-  'max_workers': $( if [ ! -z ${VIASH_PAR_MAX_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_MAX_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi )
+  'max_workers': $( if [ ! -z ${VIASH_PAR_MAX_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_MAX_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
+  'method_id': $( if [ ! -z ${VIASH_PAR_METHOD_ID+x} ]; then echo "r'${VIASH_PAR_METHOD_ID//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
   'functionality_name': $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "r'${VIASH_META_FUNCTIONALITY_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1015,20 +1035,26 @@ from main import main
 output = main(par) 
 print(output)
 # output.columns = ['S1', 'S2', 'S3', 'S4']
-output.index=[par["layer"]]
-print("Write output to file", flush=True)
-print(output)
-output.to_csv(par['score'])
+# output.index=[par["layer"]]
+# print("Write output to file", flush=True)
+# print(output)
+# output.to_csv(par['score'])
 
-# output = ad.AnnData(
-#     X=np.empty((0, 0)),
-#     uns={
-#         "layer": par["layer"],
-#         "metric_ids": output.columns.to_numpy(),
-#         "metric_values": output.values
-#     }
-# )
-# output.write_h5ad(par["score"], compression="gzip")
+print(output.values.shape, output.columns.to_numpy().shape)
+output = ad.AnnData(
+    X=np.empty((0, 0)),
+    uns={
+        "dataset_id": par["layer"],
+        "method_id": f"reg1-{par['method_id']}",
+        "metric_ids": output.columns.to_numpy(),
+        "metric_values": output.values[0]
+    }
+)
+
+
+# print(output.uns)
+
+output.write_h5ad(par["score"], compression="gzip")
 VIASHMAIN
 python -B "\$tempscript" &
 wait "\$!"
