deploy: 5db75e1bcc21122be07e613429e112d8519c0732

diff --git a/target/docker/control_methods/positive_control/positive_control b/target/docker/control_methods/positive_control/positive_control
--- a/target/docker/control_methods/positive_control/positive_control
+++ b/target/docker/control_methods/positive_control/positive_control
@@ -182,14 +182,13 @@ function ViashHelp {
   echo "        type: file, output, file must exist"
   echo "        example: resources_test/grn_models/collectri.csv"
   echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/prior/tf_all.csv"
+  echo ""
   echo "    --perturbation_data"
   echo "        type: file, file must exist"
   echo "        default: resources/grn-benchmark/perturbation_data.h5ad"
-  echo ""
-  echo "    --tf_all"
-  echo "        type: file, file must exist"
-  echo "        default: resources/prior/tf_all.csv"
-  echo "        example: resources_test/prior/tf_all.csv"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -415,9 +414,9 @@ ENTRYPOINT []
 RUN pip install --upgrade pip
 
 LABEL org.opencontainers.image.description="Companion container for running component control_methods positive_control"
-LABEL org.opencontainers.image.created="2024-09-10T18:22:09Z"
+LABEL org.opencontainers.image.created="2024-09-12T16:36:11Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="cf3016fc19ad45bc64d991be9f53c88c733a0489"
+LABEL org.opencontainers.image.revision="5db75e1bcc21122be07e613429e112d8519c0732"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -598,17 +597,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_PREDICTION=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --perturbation_data)
-            [ -n "$VIASH_PAR_PERTURBATION_DATA" ] && ViashError Bad arguments for option \'--perturbation_data\': \'$VIASH_PAR_PERTURBATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_PERTURBATION_DATA="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --perturbation_data. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --perturbation_data=*)
-            [ -n "$VIASH_PAR_PERTURBATION_DATA" ] && ViashError Bad arguments for option \'--perturbation_data=*\': \'$VIASH_PAR_PERTURBATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_PERTURBATION_DATA=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
         --tf_all)
             [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_TF_ALL="$2"
@@ -618,6 +606,17 @@ while [[ $# -gt 0 ]]; do
         --tf_all=*)
             [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --perturbation_data)
+            [ -n "$VIASH_PAR_PERTURBATION_DATA" ] && ViashError Bad arguments for option \'--perturbation_data\': \'$VIASH_PAR_PERTURBATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_PERTURBATION_DATA="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --perturbation_data. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --perturbation_data=*)
+            [ -n "$VIASH_PAR_PERTURBATION_DATA" ] && ViashError Bad arguments for option \'--perturbation_data=*\': \'$VIASH_PAR_PERTURBATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_PERTURBATION_DATA=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---setup)
@@ -738,6 +737,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -766,17 +769,14 @@ fi
 if [ -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then
   VIASH_PAR_PERTURBATION_DATA="resources/grn-benchmark/perturbation_data.h5ad"
 fi
-if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
-  VIASH_PAR_TF_ALL="resources/prior/tf_all.csv"
-fi
 
 # check whether required files exist
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
-  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
-  exit 1
-fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ] && [ ! -e "$VIASH_PAR_TF_ALL" ]; then
   ViashError "Input file '$VIASH_PAR_TF_ALL' does not exist."
+  exit 1
+fi
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ] && [ ! -e "$VIASH_PAR_PERTURBATION_DATA" ]; then
+  ViashError "Input file '$VIASH_PAR_PERTURBATION_DATA' does not exist."
   exit 1
 fi
 
@@ -836,13 +836,13 @@ if [ ! -z "$VIASH_PAR_PREDICTION" ]; then
   VIASH_PAR_PREDICTION=$(ViashAutodetectMount "$VIASH_PAR_PREDICTION")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_PREDICTION" )
 fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
-  VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_PERTURBATION_DATA")" )
-  VIASH_PAR_PERTURBATION_DATA=$(ViashAutodetectMount "$VIASH_PAR_PERTURBATION_DATA")
-fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_TF_ALL")" )
   VIASH_PAR_TF_ALL=$(ViashAutodetectMount "$VIASH_PAR_TF_ALL")
+fi
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
+  VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_PAR_PERTURBATION_DATA")" )
+  VIASH_PAR_PERTURBATION_DATA=$(ViashAutodetectMount "$VIASH_PAR_PERTURBATION_DATA")
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_EXTRA_MOUNTS+=( "$(ViashAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -914,8 +914,8 @@ from tqdm import tqdm
 par = {
   'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'prediction': $( if [ ! -z ${VIASH_PAR_PREDICTION+x} ]; then echo "r'${VIASH_PAR_PREDICTION//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'perturbation_data': $( if [ ! -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then echo "r'${VIASH_PAR_PERTURBATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'perturbation_data': $( if [ ! -z ${VIASH_PAR_PERTURBATION_DATA+x} ]; then echo "r'${VIASH_PAR_PERTURBATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
   'functionality_name': $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "r'${VIASH_META_FUNCTIONALITY_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -977,11 +977,11 @@ VIASHEOF
 if [ ! -z "$VIASH_PAR_PREDICTION" ]; then
   VIASH_PAR_PREDICTION=$(ViashStripAutomount "$VIASH_PAR_PREDICTION")
 fi
-if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
-  VIASH_PAR_PERTURBATION_DATA=$(ViashStripAutomount "$VIASH_PAR_PERTURBATION_DATA")
-fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
   VIASH_PAR_TF_ALL=$(ViashStripAutomount "$VIASH_PAR_TF_ALL")
+fi
+if [ ! -z "$VIASH_PAR_PERTURBATION_DATA" ]; then
+  VIASH_PAR_PERTURBATION_DATA=$(ViashStripAutomount "$VIASH_PAR_PERTURBATION_DATA")
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_META_RESOURCES_DIR=$(ViashStripAutomount "$VIASH_META_RESOURCES_DIR")
