deploy: 82d1465a978eb40ba3aed3e456cc9892e1d89c14

diff --git a/target/native/grn_methods/scenicplus/scenicplus b/target/native/grn_methods/scenicplus/scenicplus
--- a/target/native/grn_methods/scenicplus/scenicplus
+++ b/target/native/grn_methods/scenicplus/scenicplus
@@ -196,14 +196,20 @@ function ViashHelp {
   echo "        type: integer"
   echo "        default: 4"
   echo ""
-  echo "    --cistopic_object"
-  echo "        type: file, required parameter, output, file must exist"
-  echo "        Path to the pycistopic serialized (.pkl) object."
+  echo "    --scplus_mdata"
+  echo "        type: file, output, file must exist"
+  echo "        default: scplus_mdata.h5mu"
+  echo "        Main output object."
   echo ""
   echo "    --qc"
   echo "        type: boolean"
   echo "        default: false"
   echo "        Whether to perform quality control."
+  echo ""
+  echo "    --cell_topic"
+  echo "        type: file, required parameter, output, file must exist"
+  echo "        default: output/cell_topic.csv"
+  echo "        Cell-topics prob scores"
 }
 
 # initialise array
@@ -287,15 +293,15 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_NUM_WORKERS=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --cistopic_object)
-            [ -n "$VIASH_PAR_CISTOPIC_OBJECT" ] && ViashError Bad arguments for option \'--cistopic_object\': \'$VIASH_PAR_CISTOPIC_OBJECT\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_CISTOPIC_OBJECT="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --cistopic_object. Use "--help" to get more information on the parameters. && exit 1
+        --scplus_mdata)
+            [ -n "$VIASH_PAR_SCPLUS_MDATA" ] && ViashError Bad arguments for option \'--scplus_mdata\': \'$VIASH_PAR_SCPLUS_MDATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_SCPLUS_MDATA="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --scplus_mdata. Use "--help" to get more information on the parameters. && exit 1
             shift 2
             ;;
-        --cistopic_object=*)
-            [ -n "$VIASH_PAR_CISTOPIC_OBJECT" ] && ViashError Bad arguments for option \'--cistopic_object=*\': \'$VIASH_PAR_CISTOPIC_OBJECT\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_CISTOPIC_OBJECT=$(ViashRemoveFlags "$1")
+        --scplus_mdata=*)
+            [ -n "$VIASH_PAR_SCPLUS_MDATA" ] && ViashError Bad arguments for option \'--scplus_mdata=*\': \'$VIASH_PAR_SCPLUS_MDATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_SCPLUS_MDATA=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --qc)
@@ -307,6 +313,17 @@ while [[ $# -gt 0 ]]; do
         --qc=*)
             [ -n "$VIASH_PAR_QC" ] && ViashError Bad arguments for option \'--qc=*\': \'$VIASH_PAR_QC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_QC=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --cell_topic)
+            [ -n "$VIASH_PAR_CELL_TOPIC" ] && ViashError Bad arguments for option \'--cell_topic\': \'$VIASH_PAR_CELL_TOPIC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_CELL_TOPIC="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --cell_topic. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --cell_topic=*)
+            [ -n "$VIASH_PAR_CELL_TOPIC" ] && ViashError Bad arguments for option \'--cell_topic=*\': \'$VIASH_PAR_CELL_TOPIC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_CELL_TOPIC=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---cpus)
@@ -387,8 +404,8 @@ fi
 
 
 # check whether required parameters exist
-if [ -z ${VIASH_PAR_CISTOPIC_OBJECT+x} ]; then
-  ViashError '--cistopic_object' is a required argument. Use "--help" to get more information on the parameters.
+if [ -z ${VIASH_PAR_CELL_TOPIC+x} ]; then
+  ViashError '--cell_topic' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
@@ -427,6 +444,9 @@ if [ -z ${VIASH_PAR_TEMP_DIR+x} ]; then
 fi
 if [ -z ${VIASH_PAR_NUM_WORKERS+x} ]; then
   VIASH_PAR_NUM_WORKERS="4"
+fi
+if [ -z ${VIASH_PAR_SCPLUS_MDATA+x} ]; then
+  VIASH_PAR_SCPLUS_MDATA="scplus_mdata.h5mu"
 fi
 if [ -z ${VIASH_PAR_QC+x} ]; then
   VIASH_PAR_QC="false"
@@ -502,8 +522,11 @@ fi
 if [ ! -z "$VIASH_PAR_PREDICTION" ] && [ ! -d "$(dirname "$VIASH_PAR_PREDICTION")" ]; then
   mkdir -p "$(dirname "$VIASH_PAR_PREDICTION")"
 fi
-if [ ! -z "$VIASH_PAR_CISTOPIC_OBJECT" ] && [ ! -d "$(dirname "$VIASH_PAR_CISTOPIC_OBJECT")" ]; then
-  mkdir -p "$(dirname "$VIASH_PAR_CISTOPIC_OBJECT")"
+if [ ! -z "$VIASH_PAR_SCPLUS_MDATA" ] && [ ! -d "$(dirname "$VIASH_PAR_SCPLUS_MDATA")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_SCPLUS_MDATA")"
+fi
+if [ ! -z "$VIASH_PAR_CELL_TOPIC" ] && [ ! -d "$(dirname "$VIASH_PAR_CELL_TOPIC")" ]; then
+  mkdir -p "$(dirname "$VIASH_PAR_CELL_TOPIC")"
 fi
 
 
@@ -573,8 +596,9 @@ par = {
   'prediction': $( if [ ! -z ${VIASH_PAR_PREDICTION+x} ]; then echo "r'${VIASH_PAR_PREDICTION//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'temp_dir': $( if [ ! -z ${VIASH_PAR_TEMP_DIR+x} ]; then echo "r'${VIASH_PAR_TEMP_DIR//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
-  'cistopic_object': $( if [ ! -z ${VIASH_PAR_CISTOPIC_OBJECT+x} ]; then echo "r'${VIASH_PAR_CISTOPIC_OBJECT//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'qc': $( if [ ! -z ${VIASH_PAR_QC+x} ]; then echo "r'${VIASH_PAR_QC//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
+  'scplus_mdata': $( if [ ! -z ${VIASH_PAR_SCPLUS_MDATA+x} ]; then echo "r'${VIASH_PAR_SCPLUS_MDATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'qc': $( if [ ! -z ${VIASH_PAR_QC+x} ]; then echo "r'${VIASH_PAR_QC//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'cell_topic': $( if [ ! -z ${VIASH_PAR_CELL_TOPIC+x} ]; then echo "r'${VIASH_PAR_CELL_TOPIC//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
   'functionality_name': $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "r'${VIASH_META_FUNCTIONALITY_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -610,6 +634,8 @@ except NameError:
 out_dir = par['temp_dir']
 atac_dir = os.path.join(out_dir, 'atac')
 os.makedirs(atac_dir, exist_ok=True)
+
+par['cistopic_object'] = f"{par['temp_dir']}/cistopic_object.pkl"
 
 # Get list of samples (e.g., donors)
 print('Collect list of samples')
@@ -776,9 +802,7 @@ if not os.path.exists(os.path.join(out_dir, 'qc', 'tss.bed')):
 
 # Create cistopic objects
 if not os.path.exists(os.path.join(out_dir, 'cistopic_obj.pkl')):
-
     if par['qc']:  # Whether to perform quality control
-
         # Compute QC metrics
         print('Perform QC')
         for donor_id in unique_donor_ids:
@@ -891,7 +915,6 @@ if not os.path.exists(MALLET_PATH):
 # LDA-based topic modeling
 print('Run LDA models')
 if not os.path.exists(par['cistopic_object']):
-
     # Topic modeling
     n_topics = [2, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
     if os.path.exists(MALLET_PATH):
@@ -925,11 +948,17 @@ if not os.path.exists(par['cistopic_object']):
     model = evaluate_models(models, select_model=40, return_model=True)
     cistopic_obj.add_LDA_model(model)
 
-    with open(filepath, 'wb') as f:
+    with open(par['cistopic_object'], 'wb') as f:
         pickle.dump(cistopic_obj, f)
+    
+
 else:
-    with open(filepath, 'rb') as f:
+    with open(par['cistopic_object'], 'rb') as f:
         cistopic_obj = pickle.load(f)
+    
+cell_topic = cistopic_obj.selected_model.cell_topic.T
+cell_topic.index = cell_topic.index.str.split('-').str[0]
+cell_topic.to_csv(par['cell_topic'])
 
 chromsizes = pd.read_table(os.path.join(out_dir, "qc", "hg38.chrom_sizes_and_alias.tsv"))
 chromsizes.rename({"# ucsc": "Chromosome", "length": "End"}, axis = 1, inplace = True)
@@ -992,7 +1021,6 @@ markers_dict = find_diff_features(
     n_cpu=5,
     split_pattern='-'
 )
-
 # Save topics
 folder = os.path.join(out_dir, 'region_sets', 'Topics_otsu')
 os.makedirs(folder, exist_ok=True)
@@ -1152,10 +1180,8 @@ url = 'https://resources.aertslab.org/cistarget/motif_collections/v10nr_clust_pu
 download(url, os.path.join(DB_PATH, 'motifs-v10-nr.hgnc-m0.00001-o0.0.tbl'))
 
 if not os.path.exists(os.path.join(work_dir, 'rna.h5ad')):
-
     # Load scRNA-seq data
     adata_rna = anndata.read_h5ad(par['multiomics_rna'])
-
     # Only keep cells with at least 200 expressed genes, and genes with at least 3 cells expressing them
     sc.pp.filter_cells(adata_rna, min_genes=200)
     sc.pp.filter_genes(adata_rna, min_cells=3)
@@ -1241,6 +1267,7 @@ settings['params_data_preparation']['is_multiome'] = True
 settings['params_data_preparation']['is_multiome'] = 'key_to_group_by'
 settings['params_data_preparation']['nr_cells_per_metacells'] = 5
 settings['params_data_preparation']['species'] = 'hsapiens'
+settings['output_data']['scplus_mdata'] = par['scplus_mdata']
 
 # Save pipeline settings
 with open(os.path.join(work_dir, 'scplus_pipeline', 'Snakemake', 'config', 'config.yaml'), 'w') as f:
@@ -1252,20 +1279,17 @@ with open(os.path.join(work_dir, 'scplus_pipeline', 'Snakemake', 'config', 'conf
 with contextlib.chdir(os.path.join(work_dir, 'scplus_pipeline', 'Snakemake')):
     subprocess.run([
         'snakemake',
-        '--cores', str(par['num_workers']),
-        #'--unlock'
+        '--cores', str(par['num_workers'])
     ])
+import mudata
+scplus_mdata = mudata.read(par['scplus_mdata'])
+prediction = scplus_mdata.uns["direct_e_regulon_metadata"]
 
-# Make sure the file is properly formatted, and re-format it if needed
-filepath = os.path.join(work_dir, 'tf_to_gene_adj.tsv')
-shutil.copyfile(filepath, par['prediction'])
+prediction.to_csv(par['prediction'])
 
-
-# cistopic_obj = pickle.load(os.path.join(par['cistopic_out'], f'cistopic_object_with_model.pkl'))
-# # get cell topic association 
-# cell_topic = cistopic_obj.selected_model.cell_topic.T
-# cell_names = cistopic_obj.cell_data.obs_id.values
-# cell_topic.index = cell_names
+# # Make sure the file is properly formatted, and re-format it if needed
+# filepath = os.path.join(work_dir, 'tf_to_gene_adj.tsv')
+# shutil.copyfile(filepath, par['prediction'])
 VIASHMAIN
 python -B "\$tempscript" &
 wait "\$!"
@@ -1278,8 +1302,12 @@ if [ ! -z "$VIASH_PAR_PREDICTION" ] && [ ! -e "$VIASH_PAR_PREDICTION" ]; then
   ViashError "Output file '$VIASH_PAR_PREDICTION' does not exist."
   exit 1
 fi
-if [ ! -z "$VIASH_PAR_CISTOPIC_OBJECT" ] && [ ! -e "$VIASH_PAR_CISTOPIC_OBJECT" ]; then
-  ViashError "Output file '$VIASH_PAR_CISTOPIC_OBJECT' does not exist."
+if [ ! -z "$VIASH_PAR_SCPLUS_MDATA" ] && [ ! -e "$VIASH_PAR_SCPLUS_MDATA" ]; then
+  ViashError "Output file '$VIASH_PAR_SCPLUS_MDATA' does not exist."
+  exit 1
+fi
+if [ ! -z "$VIASH_PAR_CELL_TOPIC" ] && [ ! -e "$VIASH_PAR_CELL_TOPIC" ]; then
+  ViashError "Output file '$VIASH_PAR_CELL_TOPIC' does not exist."
   exit 1
 fi
 
