deploy: a32b952060b668ac78063a87fbb442ecf2a4d07a

diff --git a/target/docker/multiomics/format_resources_r/format_resources_r b/target/docker/multiomics/format_resources_r/format_resources_r
--- a/target/docker/multiomics/format_resources_r/format_resources_r
+++ b/target/docker/multiomics/format_resources_r/format_resources_r
@@ -174,36 +174,36 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --rna_matrix"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/X_matrix.mtx"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/X_matrix.mtx"
   echo ""
   echo "    --atac_matrix"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/X_matrix.mtx"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/X_matrix.mtx"
   echo ""
   echo "    --rna_gene_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/annotation_gene.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/annotation_gene.csv"
   echo ""
   echo "    --rna_cell_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/annotation_cell.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/annotation_cell.csv"
   echo ""
   echo "    --atac_peak_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/annotation_gene.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/annotation_gene.csv"
   echo ""
   echo "    --atac_cell_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/annotation_cell.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/annotation_cell.csv"
   echo ""
   echo "    --rna_rds"
   echo "        type: file, output, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_r/rna.rds"
+  echo "        example: resources/grn-benchmark/multiomics_r/rna.rds"
   echo ""
   echo "    --atac_rds"
   echo "        type: file, output, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_r/atac.rds"
+  echo "        example: resources/grn-benchmark/multiomics_r/atac.rds"
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -428,9 +428,9 @@ ENTRYPOINT []
  
 RUN :
 LABEL org.opencontainers.image.description="Companion container for running component multiomics format_resources_r"
-LABEL org.opencontainers.image.created="2024-10-04T21:17:17Z"
+LABEL org.opencontainers.image.created="2024-10-05T13:50:37Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="885a27d00b987b43d994c8ed66c8638af93e2e5e"
+LABEL org.opencontainers.image.revision="a32b952060b668ac78063a87fbb442ecf2a4d07a"
 LABEL org.opencontainers.image.version="build-main"
 
 VIASHDOCKER
@@ -795,6 +795,30 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_RNA_MATRIX+x} ]; then
+  ViashError '--rna_matrix' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_MATRIX+x} ]; then
+  ViashError '--atac_matrix' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_RNA_GENE_ANNOT+x} ]; then
+  ViashError '--rna_gene_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_RNA_CELL_ANNOT+x} ]; then
+  ViashError '--rna_cell_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_PEAK_ANNOT+x} ]; then
+  ViashError '--atac_peak_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_CELL_ANNOT+x} ]; then
+  ViashError '--atac_cell_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -814,32 +838,6 @@ fi
 if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   ViashError 'temp_dir' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
-fi
-
-# filling in defaults
-if [ -z ${VIASH_PAR_RNA_MATRIX+x} ]; then
-  VIASH_PAR_RNA_MATRIX="output/scRNA/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_ATAC_MATRIX+x} ]; then
-  VIASH_PAR_ATAC_MATRIX="output/scATAC/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_RNA_GENE_ANNOT+x} ]; then
-  VIASH_PAR_RNA_GENE_ANNOT="output/scRNA/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_RNA_CELL_ANNOT+x} ]; then
-  VIASH_PAR_RNA_CELL_ANNOT="output/scRNA/annotation_cell.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_PEAK_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_PEAK_ANNOT="output/scATAC/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_CELL_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_CELL_ANNOT="output/scATAC/annotation_cell.csv"
-fi
-if [ -z ${VIASH_PAR_RNA_RDS+x} ]; then
-  VIASH_PAR_RNA_RDS="resources/grn-benchmark/multiomics_r/rna.rds"
-fi
-if [ -z ${VIASH_PAR_ATAC_RDS+x} ]; then
-  VIASH_PAR_ATAC_RDS="resources/grn-benchmark/multiomics_r/atac.rds"
 fi
 
 # check whether required files exist
@@ -1072,6 +1070,7 @@ annotation_peak_filtered <- annotation_peak[filter_indices, ]
 
 # Filter the rows in X
 X_filtered <- X[filter_indices, ]
+
 
 # Create the SummarizedExperiment object with the filtered data
 atac <- SummarizedExperiment(assays = list(counts = X_filtered), 
diff --git a/target/native/multiomics/format_resources_r/format_resources_r b/target/native/multiomics/format_resources_r/format_resources_r
--- a/target/native/multiomics/format_resources_r/format_resources_r
+++ b/target/native/multiomics/format_resources_r/format_resources_r
@@ -174,36 +174,36 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --rna_matrix"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/X_matrix.mtx"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/X_matrix.mtx"
   echo ""
   echo "    --atac_matrix"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/X_matrix.mtx"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/X_matrix.mtx"
   echo ""
   echo "    --rna_gene_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/annotation_gene.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/annotation_gene.csv"
   echo ""
   echo "    --rna_cell_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scRNA/annotation_cell.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scRNA/annotation_cell.csv"
   echo ""
   echo "    --atac_peak_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/annotation_gene.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/annotation_gene.csv"
   echo ""
   echo "    --atac_cell_annot"
-  echo "        type: file, file must exist"
-  echo "        default: output/scATAC/annotation_cell.csv"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: output/scATAC/annotation_cell.csv"
   echo ""
   echo "    --rna_rds"
   echo "        type: file, output, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_r/rna.rds"
+  echo "        example: resources/grn-benchmark/multiomics_r/rna.rds"
   echo ""
   echo "    --atac_rds"
   echo "        type: file, output, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_r/atac.rds"
+  echo "        example: resources/grn-benchmark/multiomics_r/atac.rds"
 }
 
 # initialise array
@@ -398,6 +398,30 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_RNA_MATRIX+x} ]; then
+  ViashError '--rna_matrix' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_MATRIX+x} ]; then
+  ViashError '--atac_matrix' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_RNA_GENE_ANNOT+x} ]; then
+  ViashError '--rna_gene_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_RNA_CELL_ANNOT+x} ]; then
+  ViashError '--rna_cell_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_PEAK_ANNOT+x} ]; then
+  ViashError '--atac_peak_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_ATAC_CELL_ANNOT+x} ]; then
+  ViashError '--atac_cell_annot' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -417,32 +441,6 @@ fi
 if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   ViashError 'temp_dir' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
-fi
-
-# filling in defaults
-if [ -z ${VIASH_PAR_RNA_MATRIX+x} ]; then
-  VIASH_PAR_RNA_MATRIX="output/scRNA/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_ATAC_MATRIX+x} ]; then
-  VIASH_PAR_ATAC_MATRIX="output/scATAC/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_RNA_GENE_ANNOT+x} ]; then
-  VIASH_PAR_RNA_GENE_ANNOT="output/scRNA/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_RNA_CELL_ANNOT+x} ]; then
-  VIASH_PAR_RNA_CELL_ANNOT="output/scRNA/annotation_cell.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_PEAK_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_PEAK_ANNOT="output/scATAC/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_CELL_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_CELL_ANNOT="output/scATAC/annotation_cell.csv"
-fi
-if [ -z ${VIASH_PAR_RNA_RDS+x} ]; then
-  VIASH_PAR_RNA_RDS="resources/grn-benchmark/multiomics_r/rna.rds"
-fi
-if [ -z ${VIASH_PAR_ATAC_RDS+x} ]; then
-  VIASH_PAR_ATAC_RDS="resources/grn-benchmark/multiomics_r/atac.rds"
 fi
 
 # check whether required files exist
@@ -600,6 +598,7 @@ annotation_peak_filtered <- annotation_peak[filter_indices, ]
 
 # Filter the rows in X
 X_filtered <- X[filter_indices, ]
+
 
 # Create the SummarizedExperiment object with the filtered data
 atac <- SummarizedExperiment(assays = list(counts = X_filtered), 
diff --git a/target/native/multiomics/multiome_matrix/multiome_matrix b/target/native/multiomics/multiome_matrix/multiome_matrix
--- a/target/native/multiomics/multiome_matrix/multiome_matrix
+++ b/target/native/multiomics/multiome_matrix/multiome_matrix
@@ -174,36 +174,36 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    --multiomics_rna"
-  echo "        type: file, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_rna.h5ad"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources/grn-benchmark/multiomics_rna.h5ad"
   echo ""
   echo "    --multiomics_atac"
-  echo "        type: file, file must exist"
-  echo "        default: resources/grn-benchmark/multiomics_atac.h5ad"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources/grn-benchmark/multiomics_atac.h5ad"
   echo ""
   echo "    --rna_matrix"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scRNA/X_matrix.mtx"
+  echo "        example: output/scRNA/X_matrix.mtx"
   echo ""
   echo "    --atac_matrix"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scATAC/X_matrix.mtx"
+  echo "        example: output/scATAC/X_matrix.mtx"
   echo ""
   echo "    --rna_gene_annot"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scRNA/annotation_gene.csv"
+  echo "        example: output/scRNA/annotation_gene.csv"
   echo ""
   echo "    --rna_cell_annot"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scRNA/annotation_cell.csv"
+  echo "        example: output/scRNA/annotation_cell.csv"
   echo ""
   echo "    --atac_peak_annot"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scATAC/annotation_gene.csv"
+  echo "        example: output/scATAC/annotation_gene.csv"
   echo ""
   echo "    --atac_cell_annot"
   echo "        type: file, output, file must exist"
-  echo "        default: output/scATAC/annotation_cell.csv"
+  echo "        example: output/scATAC/annotation_cell.csv"
 }
 
 # initialise array
@@ -398,6 +398,14 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_MULTIOMICS_RNA+x} ]; then
+  ViashError '--multiomics_rna' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_MULTIOMICS_ATAC+x} ]; then
+  ViashError '--multiomics_atac' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -417,32 +425,6 @@ fi
 if [ -z ${VIASH_META_TEMP_DIR+x} ]; then
   ViashError 'temp_dir' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
-fi
-
-# filling in defaults
-if [ -z ${VIASH_PAR_MULTIOMICS_RNA+x} ]; then
-  VIASH_PAR_MULTIOMICS_RNA="resources/grn-benchmark/multiomics_rna.h5ad"
-fi
-if [ -z ${VIASH_PAR_MULTIOMICS_ATAC+x} ]; then
-  VIASH_PAR_MULTIOMICS_ATAC="resources/grn-benchmark/multiomics_atac.h5ad"
-fi
-if [ -z ${VIASH_PAR_RNA_MATRIX+x} ]; then
-  VIASH_PAR_RNA_MATRIX="output/scRNA/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_ATAC_MATRIX+x} ]; then
-  VIASH_PAR_ATAC_MATRIX="output/scATAC/X_matrix.mtx"
-fi
-if [ -z ${VIASH_PAR_RNA_GENE_ANNOT+x} ]; then
-  VIASH_PAR_RNA_GENE_ANNOT="output/scRNA/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_RNA_CELL_ANNOT+x} ]; then
-  VIASH_PAR_RNA_CELL_ANNOT="output/scRNA/annotation_cell.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_PEAK_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_PEAK_ANNOT="output/scATAC/annotation_gene.csv"
-fi
-if [ -z ${VIASH_PAR_ATAC_CELL_ANNOT+x} ]; then
-  VIASH_PAR_ATAC_CELL_ANNOT="output/scATAC/annotation_cell.csv"
 fi
 
 # check whether required files exist
