deploy: e039cbae7e0025d0b6ff84a10700a7a918d94444

diff --git a/target/executable/metrics/ws_distance/ws_distance b/target/executable/metrics/ws_distance/ws_distance
--- a/target/executable/metrics/ws_distance/ws_distance
+++ b/target/executable/metrics/ws_distance/ws_distance
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics ws_distance"
-LABEL org.opencontainers.image.created="2025-02-13T19:13:44Z"
+LABEL org.opencontainers.image.created="2025-02-13T22:57:19Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="c120f91de2bdc2b39efd2f4bf3f09a4684cac2fe"
+LABEL org.opencontainers.image.revision="e039cbae7e0025d0b6ff84a10700a7a918d94444"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -624,6 +624,10 @@ function ViashHelp {
   echo "        type: file"
   echo "        example:"
   echo "resources_test/grn_benchmark/prior/ws_distance_background_norman.csv"
+  echo ""
+  echo "    --silent_missing_dependencies"
+  echo "        type: boolean"
+  echo "        default: true"
   echo ""
   echo "Viash built in Computational Requirements:"
   echo "    ---cpus=INT"
@@ -794,6 +798,17 @@ while [[ $# -gt 0 ]]; do
         --ws_distance_background=*)
             [ -n "$VIASH_PAR_WS_DISTANCE_BACKGROUND" ] && ViashError Bad arguments for option \'--ws_distance_background=*\': \'$VIASH_PAR_WS_DISTANCE_BACKGROUND\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_WS_DISTANCE_BACKGROUND=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --silent_missing_dependencies)
+            [ -n "$VIASH_PAR_SILENT_MISSING_DEPENDENCIES" ] && ViashError Bad arguments for option \'--silent_missing_dependencies\': \'$VIASH_PAR_SILENT_MISSING_DEPENDENCIES\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_SILENT_MISSING_DEPENDENCIES="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --silent_missing_dependencies. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --silent_missing_dependencies=*)
+            [ -n "$VIASH_PAR_SILENT_MISSING_DEPENDENCIES" ] && ViashError Bad arguments for option \'--silent_missing_dependencies=*\': \'$VIASH_PAR_SILENT_MISSING_DEPENDENCIES\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_SILENT_MISSING_DEPENDENCIES=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---engine)
@@ -1018,6 +1033,9 @@ fi
 if [ -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then
   VIASH_PAR_APPLY_SKELETON="false"
 fi
+if [ -z ${VIASH_PAR_SILENT_MISSING_DEPENDENCIES+x} ]; then
+  VIASH_PAR_SILENT_MISSING_DEPENDENCIES="true"
+fi
 
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_PREDICTION" ] && [ ! -e "$VIASH_PAR_PREDICTION" ]; then
@@ -1057,6 +1075,12 @@ fi
 if [[ -n "$VIASH_PAR_APPLY_SKELETON" ]]; then
   if ! [[ "$VIASH_PAR_APPLY_SKELETON" =~ ^(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)$ ]]; then
     ViashError '--apply_skeleton' has to be a boolean. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+fi
+if [[ -n "$VIASH_PAR_SILENT_MISSING_DEPENDENCIES" ]]; then
+  if ! [[ "$VIASH_PAR_SILENT_MISSING_DEPENDENCIES" =~ ^(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)$ ]]; then
+    ViashError '--silent_missing_dependencies' has to be a boolean. Use "--help" to get more information on the parameters.
     exit 1
   fi
 fi
@@ -1234,6 +1258,7 @@ import anndata as ad
 import sys
 import numpy as np
 import argparse
+import os
 
 
 ## VIASH START
@@ -1249,7 +1274,8 @@ par = {
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'evaluation_data_sc': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA_SC//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'ws_consensus': $( if [ ! -z ${VIASH_PAR_WS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_WS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'ws_distance_background': $( if [ ! -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then echo "r'${VIASH_PAR_WS_DISTANCE_BACKGROUND//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'ws_distance_background': $( if [ ! -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then echo "r'${VIASH_PAR_WS_DISTANCE_BACKGROUND//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'silent_missing_dependencies': $( if [ ! -z ${VIASH_PAR_SILENT_MISSING_DEPENDENCIES+x} ]; then echo "r'${VIASH_PAR_SILENT_MISSING_DEPENDENCIES//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
 meta = {
   'name': $( if [ ! -z ${VIASH_META_NAME+x} ]; then echo "r'${VIASH_META_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1312,19 +1338,32 @@ from main import main
 
 if __name__ == '__main__':
     method_id = ad.read_h5ad(par['prediction'], backed='r').uns['method_id']
-    dataset_id = ad.read_h5ad(par['evaluation_data_sc'], backed='r').uns['dataset_id']
-    print(f"Method id: {method_id}, Dataset id: {dataset_id}")
 
-    # - main function
-    _, mean_scores = main(par)
-    print(mean_scores)
+    # - check dependencies
+    if par.get('ws_consensus') is None:
+        if par['silent_missing_dependencies']:
+            dataset_id = 'missing'
+            metric_ids =[]
+            metric_values = []
+        else:
+            raise FileNotFoundError(f"Dependencies missing {par['ws_consensus']}. Please check the paths of the dependencies")
+    else:
+        method_id = ad.read_h5ad(par['prediction'], backed='r').uns['method_id']
+        dataset_id = ad.read_h5ad(par['evaluation_data_sc'], backed='r').uns['dataset_id']
+        print(f"Method id: {method_id}, Dataset id: {dataset_id}")
+        # - main function
+        _, mean_scores = main(par)
+        print(mean_scores)
+        metric_ids = mean_scores.columns.values
+        metric_values = mean_scores.values[0]
+
     output = ad.AnnData(
         X=np.empty((0, 0)),
         uns={
             "dataset_id": dataset_id,
             "method_id": method_id,
-            "metric_ids": mean_scores.columns.values,
-            "metric_values": mean_scores.values[0]
+            "metric_ids": metric_ids,
+            "metric_values": metric_values
         }
     )
     output.write_h5ad(par['score'], compression='gzip')
