deploy: 38c8bea3e6d9fdd53abadb8aaf592fc3ab21219f

diff --git a/target/executable/metrics/ws_distance/ws_distance b/target/executable/metrics/ws_distance/ws_distance
--- a/target/executable/metrics/ws_distance/ws_distance
+++ b/target/executable/metrics/ws_distance/ws_distance
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics ws_distance"
-LABEL org.opencontainers.image.created="2025-09-21T06:56:30Z"
+LABEL org.opencontainers.image.created="2025-09-21T17:54:45Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="f850d7447ae2dda91c7241719c1681eb939de516"
+LABEL org.opencontainers.image.revision="38c8bea3e6d9fdd53abadb8aaf592fc3ab21219f"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -616,9 +616,9 @@ function ViashHelp {
   echo "        type: file, file must exist"
   echo "        example: resources_test/grn_benchmark/prior/skeleton.csv"
   echo ""
-  echo "    --evaluation_data_sc"
-  echo "        type: file, file must exist"
-  echo "        example: resources_test/grn_benchmark/evaluation_data/norman_sc.h5ad"
+  echo "    --evaluation_data"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/evaluation_data/op_bulk.h5ad"
   echo ""
   echo "    --ws_consensus"
   echo "        type: file"
@@ -782,15 +782,15 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_SKELETON=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --evaluation_data_sc)
-            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA_SC="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data_sc. Use "--help" to get more information on the parameters. && exit 1
+        --evaluation_data)
+            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data. Use "--help" to get more information on the parameters. && exit 1
             shift 2
             ;;
-        --evaluation_data_sc=*)
-            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc=*\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA_SC=$(ViashRemoveFlags "$1")
+        --evaluation_data=*)
+            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data=*\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --ws_consensus)
@@ -1004,6 +1004,10 @@ if [ -z ${VIASH_PAR_SCORE+x} ]; then
   ViashError '--score' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then
+  ViashError '--evaluation_data' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_NAME+x} ]; then
   ViashError 'name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -1061,8 +1065,8 @@ if [ ! -z "$VIASH_PAR_SKELETON" ] && [ ! -e "$VIASH_PAR_SKELETON" ]; then
   ViashError "Input file '$VIASH_PAR_SKELETON' does not exist."
   exit 1
 fi
-if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ] && [ ! -e "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
-  ViashError "Input file '$VIASH_PAR_EVALUATION_DATA_SC' does not exist."
+if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ] && [ ! -e "$VIASH_PAR_EVALUATION_DATA" ]; then
+  ViashError "Input file '$VIASH_PAR_EVALUATION_DATA' does not exist."
   exit 1
 fi
 
@@ -1197,9 +1201,9 @@ if [ ! -z "$VIASH_PAR_SKELETON" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_SKELETON")" )
   VIASH_PAR_SKELETON=$(ViashDockerAutodetectMount "$VIASH_PAR_SKELETON")
 fi
-if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
-  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA_SC")" )
-  VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA_SC")
+if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA")" )
+  VIASH_PAR_EVALUATION_DATA=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA")
 fi
 if [ ! -z "$VIASH_PAR_WS_CONSENSUS" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_WS_CONSENSUS")" )
@@ -1297,7 +1301,7 @@ par = {
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'skeleton': $( if [ ! -z ${VIASH_PAR_SKELETON+x} ]; then echo "r'${VIASH_PAR_SKELETON//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'evaluation_data_sc': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA_SC//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'evaluation_data': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'ws_consensus': $( if [ ! -z ${VIASH_PAR_WS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_WS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'ws_distance_background': $( if [ ! -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then echo "r'${VIASH_PAR_WS_DISTANCE_BACKGROUND//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'silent_missing_dependencies': $( if [ ! -z ${VIASH_PAR_SILENT_MISSING_DEPENDENCIES+x} ]; then echo "r'${VIASH_PAR_SILENT_MISSING_DEPENDENCIES//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
@@ -1382,8 +1386,8 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   if [ ! -z "$VIASH_PAR_SKELETON" ]; then
     VIASH_PAR_SKELETON=$(ViashDockerStripAutomount "$VIASH_PAR_SKELETON")
   fi
-  if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
-    VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA_SC")
+  if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
+    VIASH_PAR_EVALUATION_DATA=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA")
   fi
   if [ ! -z "$VIASH_PAR_WS_CONSENSUS" ]; then
     VIASH_PAR_WS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_WS_CONSENSUS")
