deploy: 2c98e0f40698a1b852abc5657b551f29ca355389

diff --git a/target/executable/workflows/run_grn_evaluation/run_grn_evaluation b/target/executable/workflows/run_grn_evaluation/run_grn_evaluation
--- a/target/executable/workflows/run_grn_evaluation/run_grn_evaluation
+++ b/target/executable/workflows/run_grn_evaluation/run_grn_evaluation
@@ -192,6 +192,9 @@ function ViashHelp {
   echo "    --method_id"
   echo "        type: string, required parameter"
   echo ""
+  echo "    --dataset_id"
+  echo "        type: string, required parameter"
+  echo ""
   echo "    --tf_all"
   echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
@@ -338,6 +341,17 @@ while [[ $# -gt 0 ]]; do
         --method_id=*)
             [ -n "$VIASH_PAR_METHOD_ID" ] && ViashError Bad arguments for option \'--method_id=*\': \'$VIASH_PAR_METHOD_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_METHOD_ID=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --dataset_id)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --dataset_id. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --dataset_id=*)
+            [ -n "$VIASH_PAR_DATASET_ID" ] && ViashError Bad arguments for option \'--dataset_id=*\': \'$VIASH_PAR_DATASET_ID\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_DATASET_ID=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --tf_all)
@@ -630,6 +644,10 @@ if [ -z ${VIASH_PAR_METHOD_ID+x} ]; then
   ViashError '--method_id' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
+  ViashError '--dataset_id' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
   ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -917,11 +935,13 @@ workflow run_wf {
       // use 'fromState' to fetch the arguments the component requires from the overall state
       fromState: [
         evaluation_data: "evaluation_data",
+        evaluation_data_sc: "evaluation_data_sc",
         prediction: "prediction",
         ws_distance_background: "ws_distance_background",
         subsample: "subsample",
         reg_type: "reg_type",
         method_id: "method_id",
+        dataset_id: "method_id",
         num_workers: "num_workers",
         regulators_consensus: "regulators_consensus",
         ws_consensus: "ws_consensus",
