deploy: 83dfc07f96d4e6bbf87f5bb61261ed4a7a911623

diff --git a/target/executable/metrics/regression_2/regression_2 b/target/executable/metrics/regression_2/regression_2
--- a/target/executable/metrics/regression_2/regression_2
+++ b/target/executable/metrics/regression_2/regression_2
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_2"
-LABEL org.opencontainers.image.created="2025-02-07T18:48:44Z"
+LABEL org.opencontainers.image.created="2025-02-07T19:43:03Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="613f121340161c44c1fe038a567988c3046e6cc0"
+LABEL org.opencontainers.image.revision="83dfc07f96d4e6bbf87f5bb61261ed4a7a911623"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -620,14 +620,6 @@ function ViashHelp {
   echo "        type: boolean"
   echo "        default: false"
   echo ""
-  echo "    --regulators_consensus"
-  echo "        type: file, required parameter"
-  echo "        example: resources_test/grn_benchmark/prior/regulators_consensus_op.json"
-  echo ""
-  echo "    --static_only"
-  echo "        type: boolean"
-  echo "        default: true"
-  echo ""
   echo "    --evaluation_data"
   echo "        type: file, required parameter, file must exist"
   echo "        example: resources_test/grn_benchmark/evaluation_data/op_bulk.h5ad"
@@ -640,6 +632,14 @@ function ViashHelp {
   echo "        type: string"
   echo "        default: ridge"
   echo "        name of regretion to use"
+  echo ""
+  echo "    --regulators_consensus"
+  echo "        type: file, required parameter"
+  echo "        example: resources_test/grn_benchmark/prior/regulators_consensus_op.json"
+  echo ""
+  echo "    --static_only"
+  echo "        type: boolean"
+  echo "        default: true"
   echo ""
   echo "Viash built in Computational Requirements:"
   echo "    ---cpus=INT"
@@ -801,28 +801,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_APPLY_SKELETON=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --regulators_consensus)
-            [ -n "$VIASH_PAR_REGULATORS_CONSENSUS" ] && ViashError Bad arguments for option \'--regulators_consensus\': \'$VIASH_PAR_REGULATORS_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_REGULATORS_CONSENSUS="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --regulators_consensus. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --regulators_consensus=*)
-            [ -n "$VIASH_PAR_REGULATORS_CONSENSUS" ] && ViashError Bad arguments for option \'--regulators_consensus=*\': \'$VIASH_PAR_REGULATORS_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_REGULATORS_CONSENSUS=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --static_only)
-            [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_STATIC_ONLY="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --static_only. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --static_only=*)
-            [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only=*\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_STATIC_ONLY=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
         --evaluation_data)
             [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_EVALUATION_DATA="$2"
@@ -854,6 +832,28 @@ while [[ $# -gt 0 ]]; do
         --reg_type=*)
             [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type=*\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_REG_TYPE=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --regulators_consensus)
+            [ -n "$VIASH_PAR_REGULATORS_CONSENSUS" ] && ViashError Bad arguments for option \'--regulators_consensus\': \'$VIASH_PAR_REGULATORS_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_REGULATORS_CONSENSUS="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --regulators_consensus. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --regulators_consensus=*)
+            [ -n "$VIASH_PAR_REGULATORS_CONSENSUS" ] && ViashError Bad arguments for option \'--regulators_consensus=*\': \'$VIASH_PAR_REGULATORS_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_REGULATORS_CONSENSUS=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --static_only)
+            [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_STATIC_ONLY="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --static_only. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --static_only=*)
+            [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only=*\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_STATIC_ONLY=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---engine)
@@ -1034,16 +1034,16 @@ if [ -z ${VIASH_PAR_SCORE+x} ]; then
   ViashError '--score' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
-if [ -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then
-  ViashError '--regulators_consensus' is a required argument. Use "--help" to get more information on the parameters.
-  exit 1
-fi
 if [ -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then
   ViashError '--evaluation_data' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
   ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then
+  ViashError '--regulators_consensus' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_META_NAME+x} ]; then
@@ -1093,11 +1093,11 @@ fi
 if [ -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then
   VIASH_PAR_APPLY_SKELETON="false"
 fi
-if [ -z ${VIASH_PAR_STATIC_ONLY+x} ]; then
-  VIASH_PAR_STATIC_ONLY="true"
-fi
 if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
   VIASH_PAR_REG_TYPE="ridge"
+fi
+if [ -z ${VIASH_PAR_STATIC_ONLY+x} ]; then
+  VIASH_PAR_STATIC_ONLY="true"
 fi
 
 # check whether required files exist
@@ -1241,10 +1241,6 @@ if [ ! -z "$VIASH_PAR_SCORE" ]; then
   VIASH_PAR_SCORE=$(ViashDockerAutodetectMount "$VIASH_PAR_SCORE")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_SCORE" )
 fi
-if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
-  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_REGULATORS_CONSENSUS")" )
-  VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerAutodetectMount "$VIASH_PAR_REGULATORS_CONSENSUS")
-fi
 if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA")" )
   VIASH_PAR_EVALUATION_DATA=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA")
@@ -1252,6 +1248,10 @@ fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_TF_ALL")" )
   VIASH_PAR_TF_ALL=$(ViashDockerAutodetectMount "$VIASH_PAR_TF_ALL")
+fi
+if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_REGULATORS_CONSENSUS")" )
+  VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerAutodetectMount "$VIASH_PAR_REGULATORS_CONSENSUS")
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -1339,11 +1339,11 @@ par = {
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
-  'regulators_consensus': $( if [ ! -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_REGULATORS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'evaluation_data': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'regulators_consensus': $( if [ ! -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_REGULATORS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
 meta = {
   'name': $( if [ ! -z ${VIASH_META_NAME+x} ]; then echo "r'${VIASH_META_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1438,14 +1438,14 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   if [ ! -z "$VIASH_PAR_SCORE" ]; then
     VIASH_PAR_SCORE=$(ViashDockerStripAutomount "$VIASH_PAR_SCORE")
   fi
-  if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
-    VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_REGULATORS_CONSENSUS")
-  fi
   if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
     VIASH_PAR_EVALUATION_DATA=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA")
   fi
   if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
     VIASH_PAR_TF_ALL=$(ViashDockerStripAutomount "$VIASH_PAR_TF_ALL")
+  fi
+  if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
+    VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_REGULATORS_CONSENSUS")
   fi
   if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
     VIASH_META_RESOURCES_DIR=$(ViashDockerStripAutomount "$VIASH_META_RESOURCES_DIR")
diff --git a/target/executable/metrics/ws_distance/ws_distance b/target/executable/metrics/ws_distance/ws_distance
--- a/target/executable/metrics/ws_distance/ws_distance
+++ b/target/executable/metrics/ws_distance/ws_distance
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics ws_distance"
-LABEL org.opencontainers.image.created="2025-02-07T18:48:45Z"
+LABEL org.opencontainers.image.created="2025-02-07T19:43:03Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="613f121340161c44c1fe038a567988c3046e6cc0"
+LABEL org.opencontainers.image.revision="83dfc07f96d4e6bbf87f5bb61261ed4a7a911623"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -620,6 +620,10 @@ function ViashHelp {
   echo "        type: boolean"
   echo "        default: false"
   echo ""
+  echo "    --evaluation_data_sc"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/evaluation_data/norman_sc.h5ad"
+  echo ""
   echo "    --ws_consensus"
   echo "        type: file, required parameter"
   echo "        example: resources_test/grn_benchmark/prior/ws_consensus_norman.csv"
@@ -628,10 +632,6 @@ function ViashHelp {
   echo "        type: file, required parameter"
   echo "        example:"
   echo "resources_test/grn_benchmark/prior/ws_distance_background_norman.csv"
-  echo ""
-  echo "    --evaluation_data_sc"
-  echo "        type: file, required parameter, file must exist"
-  echo "        example: resources_test/grn_benchmark/evaluation_data/norman_sc.h5ad"
   echo ""
   echo "Viash built in Computational Requirements:"
   echo "    ---cpus=INT"
@@ -793,6 +793,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_APPLY_SKELETON=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --evaluation_data_sc)
+            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA_SC="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data_sc. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --evaluation_data_sc=*)
+            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc=*\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA_SC=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --ws_consensus)
             [ -n "$VIASH_PAR_WS_CONSENSUS" ] && ViashError Bad arguments for option \'--ws_consensus\': \'$VIASH_PAR_WS_CONSENSUS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_WS_CONSENSUS="$2"
@@ -813,17 +824,6 @@ while [[ $# -gt 0 ]]; do
         --ws_distance_background=*)
             [ -n "$VIASH_PAR_WS_DISTANCE_BACKGROUND" ] && ViashError Bad arguments for option \'--ws_distance_background=*\': \'$VIASH_PAR_WS_DISTANCE_BACKGROUND\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_WS_DISTANCE_BACKGROUND=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --evaluation_data_sc)
-            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA_SC="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data_sc. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --evaluation_data_sc=*)
-            [ -n "$VIASH_PAR_EVALUATION_DATA_SC" ] && ViashError Bad arguments for option \'--evaluation_data_sc=*\': \'$VIASH_PAR_EVALUATION_DATA_SC\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA_SC=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---engine)
@@ -1004,16 +1004,16 @@ if [ -z ${VIASH_PAR_SCORE+x} ]; then
   ViashError '--score' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then
+  ViashError '--evaluation_data_sc' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_WS_CONSENSUS+x} ]; then
   ViashError '--ws_consensus' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then
   ViashError '--ws_distance_background' is a required argument. Use "--help" to get more information on the parameters.
-  exit 1
-fi
-if [ -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then
-  ViashError '--evaluation_data_sc' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_META_NAME+x} ]; then
@@ -1195,6 +1195,10 @@ if [ ! -z "$VIASH_PAR_SCORE" ]; then
   VIASH_PAR_SCORE=$(ViashDockerAutodetectMount "$VIASH_PAR_SCORE")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_SCORE" )
 fi
+if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA_SC")" )
+  VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA_SC")
+fi
 if [ ! -z "$VIASH_PAR_WS_CONSENSUS" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_WS_CONSENSUS")" )
   VIASH_PAR_WS_CONSENSUS=$(ViashDockerAutodetectMount "$VIASH_PAR_WS_CONSENSUS")
@@ -1202,10 +1206,6 @@ fi
 if [ ! -z "$VIASH_PAR_WS_DISTANCE_BACKGROUND" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_WS_DISTANCE_BACKGROUND")" )
   VIASH_PAR_WS_DISTANCE_BACKGROUND=$(ViashDockerAutodetectMount "$VIASH_PAR_WS_DISTANCE_BACKGROUND")
-fi
-if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
-  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA_SC")" )
-  VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA_SC")
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -1294,9 +1294,9 @@ par = {
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'evaluation_data_sc': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA_SC//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'ws_consensus': $( if [ ! -z ${VIASH_PAR_WS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_WS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'ws_distance_background': $( if [ ! -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then echo "r'${VIASH_PAR_WS_DISTANCE_BACKGROUND//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'evaluation_data_sc': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA_SC+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA_SC//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'ws_distance_background': $( if [ ! -z ${VIASH_PAR_WS_DISTANCE_BACKGROUND+x} ]; then echo "r'${VIASH_PAR_WS_DISTANCE_BACKGROUND//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
   'name': $( if [ ! -z ${VIASH_META_NAME+x} ]; then echo "r'${VIASH_META_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1387,14 +1387,14 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   if [ ! -z "$VIASH_PAR_SCORE" ]; then
     VIASH_PAR_SCORE=$(ViashDockerStripAutomount "$VIASH_PAR_SCORE")
   fi
+  if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
+    VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA_SC")
+  fi
   if [ ! -z "$VIASH_PAR_WS_CONSENSUS" ]; then
     VIASH_PAR_WS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_WS_CONSENSUS")
   fi
   if [ ! -z "$VIASH_PAR_WS_DISTANCE_BACKGROUND" ]; then
     VIASH_PAR_WS_DISTANCE_BACKGROUND=$(ViashDockerStripAutomount "$VIASH_PAR_WS_DISTANCE_BACKGROUND")
-  fi
-  if [ ! -z "$VIASH_PAR_EVALUATION_DATA_SC" ]; then
-    VIASH_PAR_EVALUATION_DATA_SC=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA_SC")
   fi
   if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
     VIASH_META_RESOURCES_DIR=$(ViashDockerStripAutomount "$VIASH_META_RESOURCES_DIR")
