deploy: aa9c057075992cecbcf6abe330d9608be1f89504

diff --git a/target/executable/metrics/regression_2/regression_2 b/target/executable/metrics/regression_2/regression_2
--- a/target/executable/metrics/regression_2/regression_2
+++ b/target/executable/metrics/regression_2/regression_2
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_2"
-LABEL org.opencontainers.image.created="2025-02-06T22:52:54Z"
+LABEL org.opencontainers.image.created="2025-02-07T11:03:07Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="2c98e0f40698a1b852abc5657b551f29ca355389"
+LABEL org.opencontainers.image.revision="aa9c057075992cecbcf6abe330d9608be1f89504"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -608,24 +608,6 @@ function ViashHelp {
   echo "        type: string"
   echo "        default: op"
   echo ""
-  echo "    --evaluation_data"
-  echo "        type: file, required parameter, file must exist"
-  echo "        example: resources_test/grn_benchmark/evaluation_data/op_bulk.h5ad"
-  echo ""
-  echo "    --tf_all"
-  echo "        type: file, required parameter, file must exist"
-  echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
-  echo ""
-  echo "    --reg_type"
-  echo "        type: string"
-  echo "        default: ridge"
-  echo "        name of regretion to use"
-  echo ""
-  echo "    --subsample"
-  echo "        type: integer"
-  echo "        default: -1"
-  echo "        Subsampling of perturbation data"
-  echo ""
   echo "    --num_workers"
   echo "        type: integer"
   echo "        default: 4"
@@ -645,6 +627,19 @@ function ViashHelp {
   echo "    --static_only"
   echo "        type: boolean"
   echo "        default: true"
+  echo ""
+  echo "    --evaluation_data"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/evaluation_data/op_bulk.h5ad"
+  echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
+  echo ""
+  echo "    --reg_type"
+  echo "        type: string"
+  echo "        default: ridge"
+  echo "        name of regretion to use"
   echo ""
   echo "Viash built in Computational Requirements:"
   echo "    ---cpus=INT"
@@ -773,50 +768,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_DATASET_ID=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --evaluation_data)
-            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --evaluation_data=*)
-            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data=*\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_EVALUATION_DATA=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --tf_all)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --tf_all=*)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --reg_type)
-            [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_REG_TYPE="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --reg_type. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --reg_type=*)
-            [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type=*\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_REG_TYPE=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --subsample)
-            [ -n "$VIASH_PAR_SUBSAMPLE" ] && ViashError Bad arguments for option \'--subsample\': \'$VIASH_PAR_SUBSAMPLE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_SUBSAMPLE="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --subsample. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --subsample=*)
-            [ -n "$VIASH_PAR_SUBSAMPLE" ] && ViashError Bad arguments for option \'--subsample=*\': \'$VIASH_PAR_SUBSAMPLE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_SUBSAMPLE=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
         --num_workers)
             [ -n "$VIASH_PAR_NUM_WORKERS" ] && ViashError Bad arguments for option \'--num_workers\': \'$VIASH_PAR_NUM_WORKERS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_NUM_WORKERS="$2"
@@ -870,6 +821,39 @@ while [[ $# -gt 0 ]]; do
         --static_only=*)
             [ -n "$VIASH_PAR_STATIC_ONLY" ] && ViashError Bad arguments for option \'--static_only=*\': \'$VIASH_PAR_STATIC_ONLY\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_STATIC_ONLY=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --evaluation_data)
+            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --evaluation_data. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --evaluation_data=*)
+            [ -n "$VIASH_PAR_EVALUATION_DATA" ] && ViashError Bad arguments for option \'--evaluation_data=*\': \'$VIASH_PAR_EVALUATION_DATA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_EVALUATION_DATA=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --tf_all)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --tf_all=*)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --reg_type)
+            [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_REG_TYPE="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --reg_type. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --reg_type=*)
+            [ -n "$VIASH_PAR_REG_TYPE" ] && ViashError Bad arguments for option \'--reg_type=*\': \'$VIASH_PAR_REG_TYPE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_REG_TYPE=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         ---engine)
@@ -1050,16 +1034,16 @@ if [ -z ${VIASH_PAR_SCORE+x} ]; then
   ViashError '--score' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then
+  ViashError '--regulators_consensus' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then
   ViashError '--evaluation_data' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
   ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
-  exit 1
-fi
-if [ -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then
-  ViashError '--regulators_consensus' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_META_NAME+x} ]; then
@@ -1100,12 +1084,6 @@ fi
 if [ -z ${VIASH_PAR_DATASET_ID+x} ]; then
   VIASH_PAR_DATASET_ID="op"
 fi
-if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
-  VIASH_PAR_REG_TYPE="ridge"
-fi
-if [ -z ${VIASH_PAR_SUBSAMPLE+x} ]; then
-  VIASH_PAR_SUBSAMPLE="-1"
-fi
 if [ -z ${VIASH_PAR_NUM_WORKERS+x} ]; then
   VIASH_PAR_NUM_WORKERS="4"
 fi
@@ -1117,6 +1095,9 @@ if [ -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then
 fi
 if [ -z ${VIASH_PAR_STATIC_ONLY+x} ]; then
   VIASH_PAR_STATIC_ONLY="true"
+fi
+if [ -z ${VIASH_PAR_REG_TYPE+x} ]; then
+  VIASH_PAR_REG_TYPE="ridge"
 fi
 
 # check whether required files exist
@@ -1143,12 +1124,6 @@ fi
 if [[ -n "$VIASH_PAR_VERBOSE" ]]; then
   if ! [[ "$VIASH_PAR_VERBOSE" =~ ^[-+]?[0-9]+$ ]]; then
     ViashError '--verbose' has to be an integer. Use "--help" to get more information on the parameters.
-    exit 1
-  fi
-fi
-if [[ -n "$VIASH_PAR_SUBSAMPLE" ]]; then
-  if ! [[ "$VIASH_PAR_SUBSAMPLE" =~ ^[-+]?[0-9]+$ ]]; then
-    ViashError '--subsample' has to be an integer. Use "--help" to get more information on the parameters.
     exit 1
   fi
 fi
@@ -1266,6 +1241,10 @@ if [ ! -z "$VIASH_PAR_SCORE" ]; then
   VIASH_PAR_SCORE=$(ViashDockerAutodetectMount "$VIASH_PAR_SCORE")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_SCORE" )
 fi
+if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_REGULATORS_CONSENSUS")" )
+  VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerAutodetectMount "$VIASH_PAR_REGULATORS_CONSENSUS")
+fi
 if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_EVALUATION_DATA")" )
   VIASH_PAR_EVALUATION_DATA=$(ViashDockerAutodetectMount "$VIASH_PAR_EVALUATION_DATA")
@@ -1273,10 +1252,6 @@ fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_TF_ALL")" )
   VIASH_PAR_TF_ALL=$(ViashDockerAutodetectMount "$VIASH_PAR_TF_ALL")
-fi
-if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
-  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_REGULATORS_CONSENSUS")" )
-  VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerAutodetectMount "$VIASH_PAR_REGULATORS_CONSENSUS")
 fi
 if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_META_RESOURCES_DIR")" )
@@ -1361,15 +1336,14 @@ par = {
   'max_n_links': $( if [ ! -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then echo "int(r'${VIASH_PAR_MAX_N_LINKS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'verbose': $( if [ ! -z ${VIASH_PAR_VERBOSE+x} ]; then echo "int(r'${VIASH_PAR_VERBOSE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'dataset_id': $( if [ ! -z ${VIASH_PAR_DATASET_ID+x} ]; then echo "r'${VIASH_PAR_DATASET_ID//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'evaluation_data': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'subsample': $( if [ ! -z ${VIASH_PAR_SUBSAMPLE+x} ]; then echo "int(r'${VIASH_PAR_SUBSAMPLE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'regulators_consensus': $( if [ ! -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_REGULATORS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
+  'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
+  'evaluation_data': $( if [ ! -z ${VIASH_PAR_EVALUATION_DATA+x} ]; then echo "r'${VIASH_PAR_EVALUATION_DATA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
 meta = {
   'name': $( if [ ! -z ${VIASH_META_NAME+x} ]; then echo "r'${VIASH_META_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1464,14 +1438,14 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   if [ ! -z "$VIASH_PAR_SCORE" ]; then
     VIASH_PAR_SCORE=$(ViashDockerStripAutomount "$VIASH_PAR_SCORE")
   fi
+  if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
+    VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_REGULATORS_CONSENSUS")
+  fi
   if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ]; then
     VIASH_PAR_EVALUATION_DATA=$(ViashDockerStripAutomount "$VIASH_PAR_EVALUATION_DATA")
   fi
   if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
     VIASH_PAR_TF_ALL=$(ViashDockerStripAutomount "$VIASH_PAR_TF_ALL")
-  fi
-  if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
-    VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_REGULATORS_CONSENSUS")
   fi
   if [ ! -z "$VIASH_META_RESOURCES_DIR" ]; then
     VIASH_META_RESOURCES_DIR=$(ViashDockerStripAutomount "$VIASH_META_RESOURCES_DIR")
