deploy: f5628fc0dc4321867c2562c990715151d434ec97

diff --git a/target/executable/metrics/regression_2/regression_2 b/target/executable/metrics/regression_2/regression_2
--- a/target/executable/metrics/regression_2/regression_2
+++ b/target/executable/metrics/regression_2/regression_2
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "lightgbm==4.3.0" "numpy==1.26.4" "tqdm_joblib==0.0.5"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics regression_2"
-LABEL org.opencontainers.image.created="2025-10-03T15:24:58Z"
+LABEL org.opencontainers.image.created="2025-10-08T10:57:17Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="cd7b29c7789773da6882898a3bec3057f01842c2"
+LABEL org.opencontainers.image.revision="f5628fc0dc4321867c2562c990715151d434ec97"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -594,7 +594,7 @@ function ViashHelp {
   echo ""
   echo "    --layer"
   echo "        type: string"
-  echo "        default: X_norm"
+  echo "        default: lognorm"
   echo ""
   echo "    --max_n_links"
   echo "        type: integer"
@@ -603,6 +603,10 @@ function ViashHelp {
   echo "    --verbose"
   echo "        type: integer"
   echo "        default: 2"
+  echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
   echo ""
   echo "    --num_workers"
   echo "        type: integer"
@@ -619,10 +623,6 @@ function ViashHelp {
   echo "    --skeleton"
   echo "        type: file, file must exist"
   echo "        example: resources_test/grn_benchmark/prior/skeleton.csv"
-  echo ""
-  echo "    --tf_all"
-  echo "        type: file, required parameter, file must exist"
-  echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
   echo ""
   echo "    --reg_type"
   echo "        type: string"
@@ -753,6 +753,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_VERBOSE=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --tf_all)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --tf_all=*)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --num_workers)
             [ -n "$VIASH_PAR_NUM_WORKERS" ] && ViashError Bad arguments for option \'--num_workers\': \'$VIASH_PAR_NUM_WORKERS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_NUM_WORKERS="$2"
@@ -795,17 +806,6 @@ while [[ $# -gt 0 ]]; do
         --skeleton=*)
             [ -n "$VIASH_PAR_SKELETON" ] && ViashError Bad arguments for option \'--skeleton=*\': \'$VIASH_PAR_SKELETON\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_SKELETON=$(ViashRemoveFlags "$1")
-            shift 1
-            ;;
-        --tf_all)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL="$2"
-            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
-            shift 2
-            ;;
-        --tf_all=*)
-            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
-            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --reg_type)
@@ -1058,7 +1058,7 @@ fi
 
 # filling in defaults
 if [ -z ${VIASH_PAR_LAYER+x} ]; then
-  VIASH_PAR_LAYER="X_norm"
+  VIASH_PAR_LAYER="lognorm"
 fi
 if [ -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then
   VIASH_PAR_MAX_N_LINKS="50000"
@@ -1091,12 +1091,12 @@ if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ] && [ ! -e "$VIASH_PAR_EVALUATION_DATA" 
   ViashError "Input file '$VIASH_PAR_EVALUATION_DATA' does not exist."
   exit 1
 fi
-if [ ! -z "$VIASH_PAR_SKELETON" ] && [ ! -e "$VIASH_PAR_SKELETON" ]; then
-  ViashError "Input file '$VIASH_PAR_SKELETON' does not exist."
-  exit 1
-fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ] && [ ! -e "$VIASH_PAR_TF_ALL" ]; then
   ViashError "Input file '$VIASH_PAR_TF_ALL' does not exist."
+  exit 1
+fi
+if [ ! -z "$VIASH_PAR_SKELETON" ] && [ ! -e "$VIASH_PAR_SKELETON" ]; then
+  ViashError "Input file '$VIASH_PAR_SKELETON' does not exist."
   exit 1
 fi
 
@@ -1231,13 +1231,13 @@ if [ ! -z "$VIASH_PAR_SCORE" ]; then
   VIASH_PAR_SCORE=$(ViashDockerAutodetectMount "$VIASH_PAR_SCORE")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_SCORE" )
 fi
-if [ ! -z "$VIASH_PAR_SKELETON" ]; then
-  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_SKELETON")" )
-  VIASH_PAR_SKELETON=$(ViashDockerAutodetectMount "$VIASH_PAR_SKELETON")
-fi
 if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_TF_ALL")" )
   VIASH_PAR_TF_ALL=$(ViashDockerAutodetectMount "$VIASH_PAR_TF_ALL")
+fi
+if [ ! -z "$VIASH_PAR_SKELETON" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_SKELETON")" )
+  VIASH_PAR_SKELETON=$(ViashDockerAutodetectMount "$VIASH_PAR_SKELETON")
 fi
 if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_REGULATORS_CONSENSUS")" )
@@ -1325,11 +1325,11 @@ par = {
   'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'max_n_links': $( if [ ! -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then echo "int(r'${VIASH_PAR_MAX_N_LINKS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'verbose': $( if [ ! -z ${VIASH_PAR_VERBOSE+x} ]; then echo "int(r'${VIASH_PAR_VERBOSE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'skeleton': $( if [ ! -z ${VIASH_PAR_SKELETON+x} ]; then echo "r'${VIASH_PAR_SKELETON//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'reg_type': $( if [ ! -z ${VIASH_PAR_REG_TYPE+x} ]; then echo "r'${VIASH_PAR_REG_TYPE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'regulators_consensus': $( if [ ! -z ${VIASH_PAR_REGULATORS_CONSENSUS+x} ]; then echo "r'${VIASH_PAR_REGULATORS_CONSENSUS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'static_only': $( if [ ! -z ${VIASH_PAR_STATIC_ONLY+x} ]; then echo "r'${VIASH_PAR_STATIC_ONLY//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
@@ -1401,11 +1401,11 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   if [ ! -z "$VIASH_PAR_SCORE" ]; then
     VIASH_PAR_SCORE=$(ViashDockerStripAutomount "$VIASH_PAR_SCORE")
   fi
-  if [ ! -z "$VIASH_PAR_SKELETON" ]; then
-    VIASH_PAR_SKELETON=$(ViashDockerStripAutomount "$VIASH_PAR_SKELETON")
-  fi
   if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
     VIASH_PAR_TF_ALL=$(ViashDockerStripAutomount "$VIASH_PAR_TF_ALL")
+  fi
+  if [ ! -z "$VIASH_PAR_SKELETON" ]; then
+    VIASH_PAR_SKELETON=$(ViashDockerStripAutomount "$VIASH_PAR_SKELETON")
   fi
   if [ ! -z "$VIASH_PAR_REGULATORS_CONSENSUS" ]; then
     VIASH_PAR_REGULATORS_CONSENSUS=$(ViashDockerStripAutomount "$VIASH_PAR_REGULATORS_CONSENSUS")
diff --git a/target/executable/metrics/ws_distance/ws_distance b/target/executable/metrics/ws_distance/ws_distance
--- a/target/executable/metrics/ws_distance/ws_distance
+++ b/target/executable/metrics/ws_distance/ws_distance
@@ -457,9 +457,9 @@ RUN pip install --upgrade pip && \
   pip install --upgrade --no-cache-dir "numpy==1.26.4"
 
 LABEL org.opencontainers.image.description="Companion container for running component metrics ws_distance"
-LABEL org.opencontainers.image.created="2025-10-03T15:24:58Z"
+LABEL org.opencontainers.image.created="2025-10-08T10:57:17Z"
 LABEL org.opencontainers.image.source="https://github.com/openproblems-bio/task_grn_inference"
-LABEL org.opencontainers.image.revision="cd7b29c7789773da6882898a3bec3057f01842c2"
+LABEL org.opencontainers.image.revision="f5628fc0dc4321867c2562c990715151d434ec97"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -594,7 +594,7 @@ function ViashHelp {
   echo ""
   echo "    --layer"
   echo "        type: string"
-  echo "        default: X_norm"
+  echo "        default: lognorm"
   echo ""
   echo "    --max_n_links"
   echo "        type: integer"
@@ -603,6 +603,10 @@ function ViashHelp {
   echo "    --verbose"
   echo "        type: integer"
   echo "        default: 2"
+  echo ""
+  echo "    --tf_all"
+  echo "        type: file, required parameter, file must exist"
+  echo "        example: resources_test/grn_benchmark/prior/tf_all.csv"
   echo ""
   echo "    --num_workers"
   echo "        type: integer"
@@ -747,6 +751,17 @@ while [[ $# -gt 0 ]]; do
         --verbose=*)
             [ -n "$VIASH_PAR_VERBOSE" ] && ViashError Bad arguments for option \'--verbose=*\': \'$VIASH_PAR_VERBOSE\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_VERBOSE=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --tf_all)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --tf_all. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --tf_all=*)
+            [ -n "$VIASH_PAR_TF_ALL" ] && ViashError Bad arguments for option \'--tf_all=*\': \'$VIASH_PAR_TF_ALL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_TF_ALL=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --num_workers)
@@ -1008,6 +1023,10 @@ if [ -z ${VIASH_PAR_SCORE+x} ]; then
   ViashError '--score' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_TF_ALL+x} ]; then
+  ViashError '--tf_all' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_NAME+x} ]; then
   ViashError 'name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -1035,7 +1054,7 @@ fi
 
 # filling in defaults
 if [ -z ${VIASH_PAR_LAYER+x} ]; then
-  VIASH_PAR_LAYER="X_norm"
+  VIASH_PAR_LAYER="lognorm"
 fi
 if [ -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then
   VIASH_PAR_MAX_N_LINKS="50000"
@@ -1063,6 +1082,10 @@ if [ ! -z "$VIASH_PAR_PREDICTION" ] && [ ! -e "$VIASH_PAR_PREDICTION" ]; then
 fi
 if [ ! -z "$VIASH_PAR_EVALUATION_DATA" ] && [ ! -e "$VIASH_PAR_EVALUATION_DATA" ]; then
   ViashError "Input file '$VIASH_PAR_EVALUATION_DATA' does not exist."
+  exit 1
+fi
+if [ ! -z "$VIASH_PAR_TF_ALL" ] && [ ! -e "$VIASH_PAR_TF_ALL" ]; then
+  ViashError "Input file '$VIASH_PAR_TF_ALL' does not exist."
   exit 1
 fi
 if [ ! -z "$VIASH_PAR_SKELETON" ] && [ ! -e "$VIASH_PAR_SKELETON" ]; then
@@ -1201,6 +1224,10 @@ if [ ! -z "$VIASH_PAR_SCORE" ]; then
   VIASH_PAR_SCORE=$(ViashDockerAutodetectMount "$VIASH_PAR_SCORE")
   VIASH_CHOWN_VARS+=( "$VIASH_PAR_SCORE" )
 fi
+if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
+  VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_TF_ALL")" )
+  VIASH_PAR_TF_ALL=$(ViashDockerAutodetectMount "$VIASH_PAR_TF_ALL")
+fi
 if [ ! -z "$VIASH_PAR_SKELETON" ]; then
   VIASH_DIRECTORY_MOUNTS+=( "$(ViashDockerAutodetectMountArg "$VIASH_PAR_SKELETON")" )
   VIASH_PAR_SKELETON=$(ViashDockerAutodetectMount "$VIASH_PAR_SKELETON")
@@ -1298,6 +1325,7 @@ par = {
   'layer': $( if [ ! -z ${VIASH_PAR_LAYER+x} ]; then echo "r'${VIASH_PAR_LAYER//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'max_n_links': $( if [ ! -z ${VIASH_PAR_MAX_N_LINKS+x} ]; then echo "int(r'${VIASH_PAR_MAX_N_LINKS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'verbose': $( if [ ! -z ${VIASH_PAR_VERBOSE+x} ]; then echo "int(r'${VIASH_PAR_VERBOSE//\'/\'\"\'\"r\'}')"; else echo None; fi ),
+  'tf_all': $( if [ ! -z ${VIASH_PAR_TF_ALL+x} ]; then echo "r'${VIASH_PAR_TF_ALL//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'num_workers': $( if [ ! -z ${VIASH_PAR_NUM_WORKERS+x} ]; then echo "int(r'${VIASH_PAR_NUM_WORKERS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'apply_tf': $( if [ ! -z ${VIASH_PAR_APPLY_TF+x} ]; then echo "r'${VIASH_PAR_APPLY_TF//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'apply_skeleton': $( if [ ! -z ${VIASH_PAR_APPLY_SKELETON+x} ]; then echo "r'${VIASH_PAR_APPLY_SKELETON//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
@@ -1385,6 +1413,9 @@ if [[ "$VIASH_ENGINE_TYPE" == "docker" ]]; then
   fi
   if [ ! -z "$VIASH_PAR_SCORE" ]; then
     VIASH_PAR_SCORE=$(ViashDockerStripAutomount "$VIASH_PAR_SCORE")
+  fi
+  if [ ! -z "$VIASH_PAR_TF_ALL" ]; then
+    VIASH_PAR_TF_ALL=$(ViashDockerStripAutomount "$VIASH_PAR_TF_ALL")
   fi
   if [ ! -z "$VIASH_PAR_SKELETON" ]; then
     VIASH_PAR_SKELETON=$(ViashDockerStripAutomount "$VIASH_PAR_SKELETON")
